// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (occurred_at, request_id, actor_user_id, actor_role_codes, action, resource_kind, resource_id, outcome, reason_code, detail_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, occurred_at, request_id, actor_user_id, actor_role_codes, "action", resource_kind, resource_id, outcome, reason_code, detail_json, created_at
`

type CreateAuditEventParams struct {
	OccurredAt     string
	RequestID      sql.NullString
	ActorUserID    sql.NullInt64
	ActorRoleCodes sql.NullString
	Action         string
	ResourceKind   sql.NullString
	ResourceID     sql.NullInt64
	Outcome        string
	ReasonCode     sql.NullString
	DetailJson     sql.NullString
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuditEvent,
		arg.OccurredAt,
		arg.RequestID,
		arg.ActorUserID,
		arg.ActorRoleCodes,
		arg.Action,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Outcome,
		arg.ReasonCode,
		arg.DetailJson,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.RequestID,
		&i.ActorUserID,
		&i.ActorRoleCodes,
		&i.Action,
		&i.ResourceKind,
		&i.ResourceID,
		&i.Outcome,
		&i.ReasonCode,
		&i.DetailJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, request_id, actor_user_id, actor_role_codes, "action", resource_kind, resource_id, outcome, reason_code, detail_json, created_at FROM audit_events
ORDER BY occurred_at DESC
LIMIT ? OFFSET ?
`

type ListAuditEventsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorUserID,
			&i.ActorRoleCodes,
			&i.Action,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Outcome,
			&i.ReasonCode,
			&i.DetailJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByAction = `-- name: ListAuditEventsByAction :many
SELECT id, occurred_at, request_id, actor_user_id, actor_role_codes, "action", resource_kind, resource_id, outcome, reason_code, detail_json, created_at FROM audit_events
WHERE action = ?
ORDER BY occurred_at DESC
LIMIT ? OFFSET ?
`

type ListAuditEventsByActionParams struct {
	Action string
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuditEventsByAction(ctx context.Context, arg ListAuditEventsByActionParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorUserID,
			&i.ActorRoleCodes,
			&i.Action,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Outcome,
			&i.ReasonCode,
			&i.DetailJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByActor = `-- name: ListAuditEventsByActor :many
SELECT id, occurred_at, request_id, actor_user_id, actor_role_codes, "action", resource_kind, resource_id, outcome, reason_code, detail_json, created_at FROM audit_events
WHERE actor_user_id = ?
ORDER BY occurred_at DESC
LIMIT ? OFFSET ?
`

type ListAuditEventsByActorParams struct {
	ActorUserID sql.NullInt64
	Limit       int64
	Offset      int64
}

func (q *Queries) ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByActor, arg.ActorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorUserID,
			&i.ActorRoleCodes,
			&i.Action,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Outcome,
			&i.ReasonCode,
			&i.DetailJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByResource = `-- name: ListAuditEventsByResource :many
SELECT id, occurred_at, request_id, actor_user_id, actor_role_codes, "action", resource_kind, resource_id, outcome, reason_code, detail_json, created_at FROM audit_events
WHERE resource_kind = ? AND resource_id = ?
ORDER BY occurred_at DESC
LIMIT ? OFFSET ?
`

type ListAuditEventsByResourceParams struct {
	ResourceKind sql.NullString
	ResourceID   sql.NullInt64
	Limit        int64
	Offset       int64
}

func (q *Queries) ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByResource,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorUserID,
			&i.ActorRoleCodes,
			&i.Action,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Outcome,
			&i.ReasonCode,
			&i.DetailJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
