// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const activeRolesForUser = `-- name: ActiveRolesForUser :many
SELECT urg.id, urg.role_code, urg.granted_at, r.description AS role_description
FROM user_role_grants urg
JOIN roles r ON r.code = urg.role_code
WHERE urg.user_id = ? AND urg.revoked_at IS NULL
ORDER BY urg.role_code
`

type ActiveRolesForUserRow struct {
	ID              int64
	RoleCode        string
	GrantedAt       string
	RoleDescription string
}

func (q *Queries) ActiveRolesForUser(ctx context.Context, userID int64) ([]ActiveRolesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, activeRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveRolesForUserRow{}
	for rows.Next() {
		var i ActiveRolesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleCode,
			&i.GrantedAt,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCapabilityGrant = `-- name: CreateCapabilityGrant :one
INSERT INTO user_capability_grants (user_id, capability_code, granted_by, granted_at, reason)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, capability_code, granted_by, granted_at, revoked_at, revoked_by, reason, created_at
`

type CreateCapabilityGrantParams struct {
	UserID         int64
	CapabilityCode string
	GrantedBy      int64
	GrantedAt      string
	Reason         sql.NullString
}

func (q *Queries) CreateCapabilityGrant(ctx context.Context, arg CreateCapabilityGrantParams) (UserCapabilityGrant, error) {
	row := q.db.QueryRowContext(ctx, createCapabilityGrant,
		arg.UserID,
		arg.CapabilityCode,
		arg.GrantedBy,
		arg.GrantedAt,
		arg.Reason,
	)
	var i UserCapabilityGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CapabilityCode,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createRoleGrant = `-- name: CreateRoleGrant :one
INSERT INTO user_role_grants (user_id, role_code, granted_by, granted_at, reason)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, role_code, granted_by, granted_at, revoked_at, revoked_by, reason, created_at
`

type CreateRoleGrantParams struct {
	UserID    int64
	RoleCode  string
	GrantedBy int64
	GrantedAt string
	Reason    sql.NullString
}

func (q *Queries) CreateRoleGrant(ctx context.Context, arg CreateRoleGrantParams) (UserRoleGrant, error) {
	row := q.db.QueryRowContext(ctx, createRoleGrant,
		arg.UserID,
		arg.RoleCode,
		arg.GrantedBy,
		arg.GrantedAt,
		arg.Reason,
	)
	var i UserRoleGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleCode,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const effectiveCapabilities = `-- name: EffectiveCapabilities :many
SELECT DISTINCT c.code
FROM capabilities c
WHERE c.code IN (
    -- From active role grants
    SELECT rc.capability_code
    FROM user_role_grants urg
    JOIN role_capabilities rc ON rc.role_code = urg.role_code
    WHERE urg.user_id = ? AND urg.revoked_at IS NULL
    UNION
    -- From direct capability grants
    SELECT ucg.capability_code
    FROM user_capability_grants ucg
    WHERE ucg.user_id = ? AND ucg.revoked_at IS NULL
)
ORDER BY c.code
`

type EffectiveCapabilitiesParams struct {
	UserID   int64
	UserID_2 int64
}

func (q *Queries) EffectiveCapabilities(ctx context.Context, arg EffectiveCapabilitiesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, effectiveCapabilities, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT code, description, category, created_at FROM capabilities ORDER BY code
`

func (q *Queries) ListCapabilities(ctx context.Context) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capability{}
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.Code,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleCapabilities = `-- name: ListRoleCapabilities :many
SELECT rc.role_code, rc.capability_code
FROM role_capabilities rc
ORDER BY rc.role_code, rc.capability_code
`

func (q *Queries) ListRoleCapabilities(ctx context.Context) ([]RoleCapability, error) {
	rows, err := q.db.QueryContext(ctx, listRoleCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleCapability{}
	for rows.Next() {
		var i RoleCapability
		if err := rows.Scan(&i.RoleCode, &i.CapabilityCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT code, description, kind, created_at FROM roles ORDER BY code
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.Code,
			&i.Description,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCapabilityGrant = `-- name: RevokeCapabilityGrant :exec
UPDATE user_capability_grants
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    revoked_by = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeCapabilityGrantParams struct {
	RevokedBy sql.NullInt64
	ID        int64
}

func (q *Queries) RevokeCapabilityGrant(ctx context.Context, arg RevokeCapabilityGrantParams) error {
	_, err := q.db.ExecContext(ctx, revokeCapabilityGrant, arg.RevokedBy, arg.ID)
	return err
}

const revokeRoleGrant = `-- name: RevokeRoleGrant :exec
UPDATE user_role_grants
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    revoked_by = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeRoleGrantParams struct {
	RevokedBy sql.NullInt64
	ID        int64
}

func (q *Queries) RevokeRoleGrant(ctx context.Context, arg RevokeRoleGrantParams) error {
	_, err := q.db.ExecContext(ctx, revokeRoleGrant, arg.RevokedBy, arg.ID)
	return err
}

const roleExists = `-- name: RoleExists :one
SELECT EXISTS(SELECT 1 FROM roles WHERE code = ?) AS found
`

func (q *Queries) RoleExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, roleExists, code)
	var found bool
	err := row.Scan(&found)
	return found, err
}
