// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authn.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const consumeEmailLink = `-- name: ConsumeEmailLink :exec
UPDATE email_links SET consumed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) ConsumeEmailLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, consumeEmailLink, id)
	return err
}

const createEmailLink = `-- name: CreateEmailLink :one
INSERT INTO email_links (purpose, user_id, email, token_hash, created_at, expires_at, requested_ip_hash)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, purpose, user_id, email, token_hash, created_at, expires_at, consumed_at, requested_ip_hash, intended_role_code
`

type CreateEmailLinkParams struct {
	Purpose         string
	UserID          sql.NullInt64
	Email           string
	TokenHash       string
	CreatedAt       string
	ExpiresAt       string
	RequestedIpHash sql.NullString
}

func (q *Queries) CreateEmailLink(ctx context.Context, arg CreateEmailLinkParams) (EmailLink, error) {
	row := q.db.QueryRowContext(ctx, createEmailLink,
		arg.Purpose,
		arg.UserID,
		arg.Email,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RequestedIpHash,
	)
	var i EmailLink
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RequestedIpHash,
		&i.IntendedRoleCode,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, created_at, last_seen_at, expires_at, ip_hash, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         string
	UserID     int64
	CreatedAt  string
	LastSeenAt string
	ExpiresAt  string
	IpHash     sql.NullString
	UserAgent  sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.IpHash,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, password_algo_params, person_id)
VALUES (?, ?, ?, ?)
RETURNING id, email, email_verified_at, password_hash, password_algo_params, person_id, is_active, last_login_at, failed_login_count, locked_until, created_at, updated_at, version, text_size
`

type CreateUserParams struct {
	Email              string
	PasswordHash       sql.NullString
	PasswordAlgoParams sql.NullString
	PersonID           sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordAlgoParams,
		arg.PersonID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordAlgoParams,
		&i.PersonID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TextSize,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const getEmailLinkByTokenHash = `-- name: GetEmailLinkByTokenHash :one
SELECT id, purpose, user_id, email, token_hash, created_at, expires_at, consumed_at, requested_ip_hash, intended_role_code FROM email_links
WHERE token_hash = ? AND consumed_at IS NULL AND expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

func (q *Queries) GetEmailLinkByTokenHash(ctx context.Context, tokenHash string) (EmailLink, error) {
	row := q.db.QueryRowContext(ctx, getEmailLinkByTokenHash, tokenHash)
	var i EmailLink
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RequestedIpHash,
		&i.IntendedRoleCode,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, last_seen_at, expires_at, ip_hash, user_agent, revoked_at FROM sessions WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IpHash,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_verified_at, password_hash, password_algo_params, person_id, is_active, last_login_at, failed_login_count, locked_until, created_at, updated_at, version, text_size FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordAlgoParams,
		&i.PersonID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TextSize,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, password_hash, password_algo_params, person_id, is_active, last_login_at, failed_login_count, locked_until, created_at, updated_at, version, text_size FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordAlgoParams,
		&i.PersonID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TextSize,
	)
	return i, err
}

const getUserTextSize = `-- name: GetUserTextSize :one
SELECT text_size FROM users WHERE id = ?
`

func (q *Queries) GetUserTextSize(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserTextSize, id)
	var text_size string
	err := row.Scan(&text_size)
	return text_size, err
}

const incrementFailedLogin = `-- name: IncrementFailedLogin :exec
UPDATE users
SET failed_login_count = failed_login_count + 1,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) IncrementFailedLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementFailedLogin, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, person_id, is_active, last_login_at, created_at
FROM users
ORDER BY email
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64
	Offset int64
}

type ListUsersRow struct {
	ID          int64
	Email       string
	PersonID    sql.NullInt64
	IsActive    int64
	LastLoginAt sql.NullString
	CreatedAt   string
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PersonID,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type LockUserParams struct {
	LockedUntil sql.NullString
	ID          int64
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.ExecContext(ctx, lockUser, arg.LockedUntil, arg.ID)
	return err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const setUserTextSize = `-- name: SetUserTextSize :exec
UPDATE users
SET text_size = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetUserTextSizeParams struct {
	TextSize string
	ID       int64
}

func (q *Queries) SetUserTextSize(ctx context.Context, arg SetUserTextSizeParams) error {
	_, err := q.db.ExecContext(ctx, setUserTextSize, arg.TextSize, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastSeenAt string
	ID         string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.ID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    failed_login_count = 0,
    locked_until = NULL,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = ?, password_algo_params = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, email, email_verified_at, password_hash, password_algo_params, person_id, is_active, last_login_at, failed_login_count, locked_until, created_at, updated_at, version, text_size
`

type UpdateUserPasswordParams struct {
	PasswordHash       sql.NullString
	PasswordAlgoParams sql.NullString
	ID                 int64
	Version            int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword,
		arg.PasswordHash,
		arg.PasswordAlgoParams,
		arg.ID,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.PasswordAlgoParams,
		&i.PersonID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TextSize,
	)
	return i, err
}
