// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :exec
UPDATE idempotency_records
SET resource_kind = ?, resource_id = ?
WHERE id = ?
`

type CompleteIdempotencyRecordParams struct {
	ResourceKind sql.NullString
	ResourceID   sql.NullInt64
	ID           int64
}

// Records which resource a claimed key produced, so a retry can return the
// original result instead of doing the work twice.
func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) error {
	_, err := q.db.ExecContext(ctx, completeIdempotencyRecord, arg.ResourceKind, arg.ResourceID, arg.ID)
	return err
}

const getPaymentBatchEntry = `-- name: GetPaymentBatchEntry :one
SELECT id, batch_id, membership_id, sequence, amount_cents, method, reference, received_on, received_by_officer, paid_through, treasurer_note, created_at, updated_at, version FROM payment_batch_entries WHERE id = ?
`

func (q *Queries) GetPaymentBatchEntry(ctx context.Context, id int64) (PaymentBatchEntry, error) {
	row := q.db.QueryRowContext(ctx, getPaymentBatchEntry, id)
	var i PaymentBatchEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.MembershipID,
		&i.Sequence,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.ReceivedOn,
		&i.ReceivedByOfficer,
		&i.PaidThrough,
		&i.TreasurerNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPaymentBatchTotals = `-- name: GetPaymentBatchTotals :one
SELECT
    COUNT(*)                                                          AS entry_count,
    CAST(COALESCE(SUM(amount_cents), 0) AS INTEGER)                   AS net_total_cents,
    CAST(COALESCE(SUM(CASE WHEN method = 'cash'  THEN 1 ELSE 0 END), 0) AS INTEGER)            AS cash_count,
    CAST(COALESCE(SUM(CASE WHEN method = 'cash'  THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS cash_total_cents,
    CAST(COALESCE(SUM(CASE WHEN method = 'check' THEN 1 ELSE 0 END), 0) AS INTEGER)            AS check_count,
    CAST(COALESCE(SUM(CASE WHEN method = 'check' THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS check_total_cents,
    CAST(COALESCE(SUM(CASE WHEN method = 'other' THEN 1 ELSE 0 END), 0) AS INTEGER)            AS other_count,
    CAST(COALESCE(SUM(CASE WHEN method = 'other' THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS other_total_cents
FROM payment_batch_entries
WHERE batch_id = ?
`

type GetPaymentBatchTotalsRow struct {
	EntryCount      int64
	NetTotalCents   int64
	CashCount       int64
	CashTotalCents  int64
	CheckCount      int64
	CheckTotalCents int64
	OtherCount      int64
	OtherTotalCents int64
}

// Totals are always calculated by the server. A client never submits one.
func (q *Queries) GetPaymentBatchTotals(ctx context.Context, batchID int64) (GetPaymentBatchTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentBatchTotals, batchID)
	var i GetPaymentBatchTotalsRow
	err := row.Scan(
		&i.EntryCount,
		&i.NetTotalCents,
		&i.CashCount,
		&i.CashTotalCents,
		&i.CheckCount,
		&i.CheckTotalCents,
		&i.OtherCount,
		&i.OtherTotalCents,
	)
	return i, err
}

const listPaymentBatches = `-- name: ListPaymentBatches :many

SELECT id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version FROM payment_batches
WHERE (CAST(?1 AS TEXT) = ''
       OR state = CAST(?1 AS TEXT))
ORDER BY opened_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListPaymentBatchesParams struct {
	StateFilter string
	Off         int64
	Lim         int64
}

// Draft payment batches and their mutable entries.
//
// Nothing in this file writes a payment or a coverage event. A draft batch is
// deliberately inert until it is posted.
func (q *Queries) ListPaymentBatches(ctx context.Context, arg ListPaymentBatchesParams) ([]PaymentBatch, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentBatches, arg.StateFilter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentBatch{}
	for rows.Next() {
		var i PaymentBatch
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.State,
			&i.DefaultAmountCents,
			&i.DefaultPaidThrough,
			&i.OpenedBy,
			&i.OpenedAt,
			&i.PostedBy,
			&i.PostedAt,
			&i.AbandonedBy,
			&i.AbandonedAt,
			&i.AbandonReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPaymentBatchEntrySequence = `-- name: NextPaymentBatchEntrySequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) + 1 AS INTEGER) AS next_sequence
FROM payment_batch_entries WHERE batch_id = ?
`

// Sequence is stable and server-assigned: removing row 2 never renumbers row 3,
// so a printed worksheet and the grid keep agreeing.
func (q *Queries) NextPaymentBatchEntrySequence(ctx context.Context, batchID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextPaymentBatchEntrySequence, batchID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const touchPaymentBatch = `-- name: TouchPaymentBatch :one
UPDATE payment_batches
SET version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'open'
RETURNING id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version
`

// Bumps the batch version after an entry mutation, so a browser holding a
// stale batch ETag cannot post a batch whose rows have since changed.
func (q *Queries) TouchPaymentBatch(ctx context.Context, id int64) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, touchPaymentBatch, id)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.State,
		&i.DefaultAmountCents,
		&i.DefaultPaidThrough,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.AbandonedBy,
		&i.AbandonedAt,
		&i.AbandonReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updatePaymentBatchDefaults = `-- name: UpdatePaymentBatchDefaults :one
UPDATE payment_batches
SET label = ?, default_amount_cents = ?, default_paid_through = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ? AND state = 'open'
RETURNING id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version
`

type UpdatePaymentBatchDefaultsParams struct {
	Label              string
	DefaultAmountCents sql.NullInt64
	DefaultPaidThrough sql.NullString
	ID                 int64
	Version            int64
}

// Version-guarded, and refuses a terminal batch: a posted or abandoned batch
// accepts no further changes.
func (q *Queries) UpdatePaymentBatchDefaults(ctx context.Context, arg UpdatePaymentBatchDefaultsParams) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentBatchDefaults,
		arg.Label,
		arg.DefaultAmountCents,
		arg.DefaultPaidThrough,
		arg.ID,
		arg.Version,
	)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.State,
		&i.DefaultAmountCents,
		&i.DefaultPaidThrough,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.AbandonedBy,
		&i.AbandonedAt,
		&i.AbandonReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updatePaymentBatchEntry = `-- name: UpdatePaymentBatchEntry :one
UPDATE payment_batch_entries
SET membership_id = ?, amount_cents = ?, method = ?, reference = ?,
    received_on = ?, received_by_officer = ?, paid_through = ?, treasurer_note = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, batch_id, membership_id, sequence, amount_cents, method, reference, received_on, received_by_officer, paid_through, treasurer_note, created_at, updated_at, version
`

type UpdatePaymentBatchEntryParams struct {
	MembershipID      int64
	AmountCents       int64
	Method            string
	Reference         sql.NullString
	ReceivedOn        string
	ReceivedByOfficer sql.NullString
	PaidThrough       string
	TreasurerNote     sql.NullString
	ID                int64
	Version           int64
}

func (q *Queries) UpdatePaymentBatchEntry(ctx context.Context, arg UpdatePaymentBatchEntryParams) (PaymentBatchEntry, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentBatchEntry,
		arg.MembershipID,
		arg.AmountCents,
		arg.Method,
		arg.Reference,
		arg.ReceivedOn,
		arg.ReceivedByOfficer,
		arg.PaidThrough,
		arg.TreasurerNote,
		arg.ID,
		arg.Version,
	)
	var i PaymentBatchEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.MembershipID,
		&i.Sequence,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.ReceivedOn,
		&i.ReceivedByOfficer,
		&i.PaidThrough,
		&i.TreasurerNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
