// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_requests.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countPendingChangeRequestItems = `-- name: CountPendingChangeRequestItems :one
SELECT count(*) FROM member_change_request_items
 WHERE request_id = ? AND status = 'pending'
`

// A request resolves only when this reaches zero.
func (q *Queries) CountPendingChangeRequestItems(ctx context.Context, requestID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingChangeRequestItems, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChangeRequest = `-- name: CreateChangeRequest :one

INSERT INTO member_change_requests (
    source, status, requester_user_id, target_person_id,
    supplied_name, supplied_call_sign, supplied_contact, stated_relationship,
    summary, received_by, submitted_at, source_ip_hash
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source, status, requester_user_id, target_person_id, supplied_name, supplied_call_sign, supplied_contact, stated_relationship, summary, received_by, submitted_at, triaged_by, triaged_at, resolved_at, withdrawn_at, source_ip_hash, created_at, updated_at, version
`

type CreateChangeRequestParams struct {
	Source             string
	Status             string
	RequesterUserID    sql.NullInt64
	TargetPersonID     sql.NullInt64
	SuppliedName       sql.NullString
	SuppliedCallSign   sql.NullString
	SuppliedContact    sql.NullString
	StatedRelationship sql.NullString
	Summary            string
	ReceivedBy         sql.NullInt64
	SubmittedAt        string
	SourceIpHash       sql.NullString
}

// Member change requests and their typed items.
//
// No query in this file writes persons, contact_methods, memberships, or
// preference events. A request records what someone PROPOSED; only the review
// and apply path (bcars-portal-4ux.3) calls the domain services that change
// canonical data, and only for an approved item.
//
// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
// offset, so a multi-byte character above a query corrupts the SQL it parses.
func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (MemberChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, createChangeRequest,
		arg.Source,
		arg.Status,
		arg.RequesterUserID,
		arg.TargetPersonID,
		arg.SuppliedName,
		arg.SuppliedCallSign,
		arg.SuppliedContact,
		arg.StatedRelationship,
		arg.Summary,
		arg.ReceivedBy,
		arg.SubmittedAt,
		arg.SourceIpHash,
	)
	var i MemberChangeRequest
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.RequesterUserID,
		&i.TargetPersonID,
		&i.SuppliedName,
		&i.SuppliedCallSign,
		&i.SuppliedContact,
		&i.StatedRelationship,
		&i.Summary,
		&i.ReceivedBy,
		&i.SubmittedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ResolvedAt,
		&i.WithdrawnAt,
		&i.SourceIpHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createChangeRequestItem = `-- name: CreateChangeRequestItem :one
INSERT INTO member_change_request_items (
    request_id, ordinal, operation, proposed_value,
    target_kind, target_id, target_version, sensitivity
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, request_id, ordinal, operation, proposed_value, target_kind, target_id, target_version, sensitivity, status, reviewed_by, reviewed_at, decision_reason, verification_note, applied_at, applied_resource_kind, applied_resource_id, applied_resource_version, created_at, updated_at, version, applied_value
`

type CreateChangeRequestItemParams struct {
	RequestID     int64
	Ordinal       int64
	Operation     string
	ProposedValue sql.NullString
	TargetKind    sql.NullString
	TargetID      sql.NullInt64
	TargetVersion sql.NullInt64
	Sensitivity   string
}

func (q *Queries) CreateChangeRequestItem(ctx context.Context, arg CreateChangeRequestItemParams) (MemberChangeRequestItem, error) {
	row := q.db.QueryRowContext(ctx, createChangeRequestItem,
		arg.RequestID,
		arg.Ordinal,
		arg.Operation,
		arg.ProposedValue,
		arg.TargetKind,
		arg.TargetID,
		arg.TargetVersion,
		arg.Sensitivity,
	)
	var i MemberChangeRequestItem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Ordinal,
		&i.Operation,
		&i.ProposedValue,
		&i.TargetKind,
		&i.TargetID,
		&i.TargetVersion,
		&i.Sensitivity,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.VerificationNote,
		&i.AppliedAt,
		&i.AppliedResourceKind,
		&i.AppliedResourceID,
		&i.AppliedResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AppliedValue,
	)
	return i, err
}

const decideChangeRequestItem = `-- name: DecideChangeRequestItem :one
UPDATE member_change_request_items
   SET status = ?1,
       reviewed_by = ?2,
       reviewed_at = ?3,
       decision_reason = ?4,
       verification_note = ?5,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?6
   AND version = ?7
   AND status = 'pending'
RETURNING id, request_id, ordinal, operation, proposed_value, target_kind, target_id, target_version, sensitivity, status, reviewed_by, reviewed_at, decision_reason, verification_note, applied_at, applied_resource_kind, applied_resource_id, applied_resource_version, created_at, updated_at, version, applied_value
`

type DecideChangeRequestItemParams struct {
	Status           string
	ReviewedBy       sql.NullInt64
	ReviewedAt       sql.NullString
	DecisionReason   sql.NullString
	VerificationNote sql.NullString
	ID               int64
	Version          int64
}

// Records a decision without applying anything. Guarded on the item version
// AND on still being pending, so a second reviewer deciding the same item gets
// no rows rather than overwriting the first decision.
func (q *Queries) DecideChangeRequestItem(ctx context.Context, arg DecideChangeRequestItemParams) (MemberChangeRequestItem, error) {
	row := q.db.QueryRowContext(ctx, decideChangeRequestItem,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.DecisionReason,
		arg.VerificationNote,
		arg.ID,
		arg.Version,
	)
	var i MemberChangeRequestItem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Ordinal,
		&i.Operation,
		&i.ProposedValue,
		&i.TargetKind,
		&i.TargetID,
		&i.TargetVersion,
		&i.Sensitivity,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.VerificationNote,
		&i.AppliedAt,
		&i.AppliedResourceKind,
		&i.AppliedResourceID,
		&i.AppliedResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AppliedValue,
	)
	return i, err
}

const getChangeRequest = `-- name: GetChangeRequest :one
SELECT id, source, status, requester_user_id, target_person_id, supplied_name, supplied_call_sign, supplied_contact, stated_relationship, summary, received_by, submitted_at, triaged_by, triaged_at, resolved_at, withdrawn_at, source_ip_hash, created_at, updated_at, version FROM member_change_requests WHERE id = ?
`

func (q *Queries) GetChangeRequest(ctx context.Context, id int64) (MemberChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, getChangeRequest, id)
	var i MemberChangeRequest
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.RequesterUserID,
		&i.TargetPersonID,
		&i.SuppliedName,
		&i.SuppliedCallSign,
		&i.SuppliedContact,
		&i.StatedRelationship,
		&i.Summary,
		&i.ReceivedBy,
		&i.SubmittedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ResolvedAt,
		&i.WithdrawnAt,
		&i.SourceIpHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getChangeRequestItem = `-- name: GetChangeRequestItem :one
SELECT id, request_id, ordinal, operation, proposed_value, target_kind, target_id, target_version, sensitivity, status, reviewed_by, reviewed_at, decision_reason, verification_note, applied_at, applied_resource_kind, applied_resource_id, applied_resource_version, created_at, updated_at, version, applied_value FROM member_change_request_items WHERE id = ?
`

func (q *Queries) GetChangeRequestItem(ctx context.Context, id int64) (MemberChangeRequestItem, error) {
	row := q.db.QueryRowContext(ctx, getChangeRequestItem, id)
	var i MemberChangeRequestItem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Ordinal,
		&i.Operation,
		&i.ProposedValue,
		&i.TargetKind,
		&i.TargetID,
		&i.TargetVersion,
		&i.Sensitivity,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.VerificationNote,
		&i.AppliedAt,
		&i.AppliedResourceKind,
		&i.AppliedResourceID,
		&i.AppliedResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AppliedValue,
	)
	return i, err
}

const listChangeRequestItems = `-- name: ListChangeRequestItems :many
SELECT id, request_id, ordinal, operation, proposed_value, target_kind, target_id, target_version, sensitivity, status, reviewed_by, reviewed_at, decision_reason, verification_note, applied_at, applied_resource_kind, applied_resource_id, applied_resource_version, created_at, updated_at, version, applied_value FROM member_change_request_items
 WHERE request_id = ?
 ORDER BY ordinal
`

func (q *Queries) ListChangeRequestItems(ctx context.Context, requestID int64) ([]MemberChangeRequestItem, error) {
	rows, err := q.db.QueryContext(ctx, listChangeRequestItems, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberChangeRequestItem{}
	for rows.Next() {
		var i MemberChangeRequestItem
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Ordinal,
			&i.Operation,
			&i.ProposedValue,
			&i.TargetKind,
			&i.TargetID,
			&i.TargetVersion,
			&i.Sensitivity,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.VerificationNote,
			&i.AppliedAt,
			&i.AppliedResourceKind,
			&i.AppliedResourceID,
			&i.AppliedResourceVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.AppliedValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeRequests = `-- name: ListChangeRequests :many
SELECT r.id, r.source, r.status, r.requester_user_id, r.target_person_id, r.supplied_name, r.supplied_call_sign, r.supplied_contact, r.stated_relationship, r.summary, r.received_by, r.submitted_at, r.triaged_by, r.triaged_at, r.resolved_at, r.withdrawn_at, r.source_ip_hash, r.created_at, r.updated_at, r.version,
       p.display_name AS target_display_name
  FROM member_change_requests r
  LEFT JOIN persons p ON p.id = r.target_person_id
 WHERE (?1 IS NULL OR r.status = ?1)
   AND (?2 IS NULL OR r.source = ?2)
   AND (?3 IS NULL
        OR r.requester_user_id = ?3)
   AND (?4 = 0
        OR (r.target_person_id IS NULL
            AND r.status NOT IN ('resolved', 'withdrawn')))
 ORDER BY r.submitted_at DESC, r.id DESC
 -- Named, not bare ` + "`" + `?` + "`" + `. sqlc numbers named parameters (?3, ?4, ...) and leaves
 -- a bare ` + "`" + `?` + "`" + ` positional, so mixing the two in one query makes SQLite expect
 -- arguments at indices the generated call never binds. That fails at runtime
 -- with "missing argument with index N", not at generation time.
 LIMIT ?6 OFFSET ?5
`

type ListChangeRequestsParams struct {
	Status          interface{}
	Source          interface{}
	RequesterUserID interface{}
	UntargetedOnly  interface{}
	PageOffset      int64
	PageLimit       int64
}

type ListChangeRequestsRow struct {
	ID                 int64
	Source             string
	Status             string
	RequesterUserID    sql.NullInt64
	TargetPersonID     sql.NullInt64
	SuppliedName       sql.NullString
	SuppliedCallSign   sql.NullString
	SuppliedContact    sql.NullString
	StatedRelationship sql.NullString
	Summary            string
	ReceivedBy         sql.NullInt64
	SubmittedAt        string
	TriagedBy          sql.NullInt64
	TriagedAt          sql.NullString
	ResolvedAt         sql.NullString
	WithdrawnAt        sql.NullString
	SourceIpHash       sql.NullString
	CreatedAt          string
	UpdatedAt          string
	Version            int64
	TargetDisplayName  sql.NullString
}

// The officer queue. Every filter is optional: pass NULL for status, source, or
// requester to ignore it, and 0 for untargeted_only to include linked requests.
//
// Ordering is submitted_at DESC with an id tie-breaker so a page boundary is
// deterministic. Without the tie-breaker two requests recorded in the same
// millisecond could swap places between calls and hide a row from a caller
// paging through the queue.
func (q *Queries) ListChangeRequests(ctx context.Context, arg ListChangeRequestsParams) ([]ListChangeRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangeRequests,
		arg.Status,
		arg.Source,
		arg.RequesterUserID,
		arg.UntargetedOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChangeRequestsRow{}
	for rows.Next() {
		var i ListChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Status,
			&i.RequesterUserID,
			&i.TargetPersonID,
			&i.SuppliedName,
			&i.SuppliedCallSign,
			&i.SuppliedContact,
			&i.StatedRelationship,
			&i.Summary,
			&i.ReceivedBy,
			&i.SubmittedAt,
			&i.TriagedBy,
			&i.TriagedAt,
			&i.ResolvedAt,
			&i.WithdrawnAt,
			&i.SourceIpHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.TargetDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeRequestsForRequester = `-- name: ListChangeRequestsForRequester :many
SELECT id, source, status, requester_user_id, target_person_id, supplied_name, supplied_call_sign, supplied_contact, stated_relationship, summary, received_by, submitted_at, triaged_by, triaged_at, resolved_at, withdrawn_at, source_ip_hash, created_at, updated_at, version FROM member_change_requests
 WHERE requester_user_id = ?
 ORDER BY submitted_at DESC, id DESC
 LIMIT ? OFFSET ?
`

type ListChangeRequestsForRequesterParams struct {
	RequesterUserID sql.NullInt64
	Limit           int64
	Offset          int64
}

// A member's own request history. Scoped by requester, never by target, so it
// cannot become a read of someone else's record.
func (q *Queries) ListChangeRequestsForRequester(ctx context.Context, arg ListChangeRequestsForRequesterParams) ([]MemberChangeRequest, error) {
	rows, err := q.db.QueryContext(ctx, listChangeRequestsForRequester, arg.RequesterUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberChangeRequest{}
	for rows.Next() {
		var i MemberChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Status,
			&i.RequesterUserID,
			&i.TargetPersonID,
			&i.SuppliedName,
			&i.SuppliedCallSign,
			&i.SuppliedContact,
			&i.StatedRelationship,
			&i.Summary,
			&i.ReceivedBy,
			&i.SubmittedAt,
			&i.TriagedBy,
			&i.TriagedAt,
			&i.ResolvedAt,
			&i.WithdrawnAt,
			&i.SourceIpHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntargetedChangeRequests = `-- name: ListUntargetedChangeRequests :many
SELECT id, source, status, requester_user_id, target_person_id, supplied_name, supplied_call_sign, supplied_contact, stated_relationship, summary, received_by, submitted_at, triaged_by, triaged_at, resolved_at, withdrawn_at, source_ip_hash, created_at, updated_at, version FROM member_change_requests
 WHERE target_person_id IS NULL
   AND status NOT IN ('resolved', 'withdrawn')
 ORDER BY submitted_at DESC, id DESC
 LIMIT ? OFFSET ?
`

type ListUntargetedChangeRequestsParams struct {
	Limit  int64
	Offset int64
}

// Blind public intake awaiting an officer link.
func (q *Queries) ListUntargetedChangeRequests(ctx context.Context, arg ListUntargetedChangeRequestsParams) ([]MemberChangeRequest, error) {
	rows, err := q.db.QueryContext(ctx, listUntargetedChangeRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberChangeRequest{}
	for rows.Next() {
		var i MemberChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Status,
			&i.RequesterUserID,
			&i.TargetPersonID,
			&i.SuppliedName,
			&i.SuppliedCallSign,
			&i.SuppliedContact,
			&i.StatedRelationship,
			&i.Summary,
			&i.ReceivedBy,
			&i.SubmittedAt,
			&i.TriagedBy,
			&i.TriagedAt,
			&i.ResolvedAt,
			&i.WithdrawnAt,
			&i.SourceIpHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChangeRequestItemApplied = `-- name: MarkChangeRequestItemApplied :one
UPDATE member_change_request_items
   SET applied_at = ?1,
       applied_value = ?2,
       applied_resource_kind = ?3,
       applied_resource_id = ?4,
       applied_resource_version = ?5,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?6
   AND version = ?7
   AND status = 'approved'
   AND applied_at IS NULL
RETURNING id, request_id, ordinal, operation, proposed_value, target_kind, target_id, target_version, sensitivity, status, reviewed_by, reviewed_at, decision_reason, verification_note, applied_at, applied_resource_kind, applied_resource_id, applied_resource_version, created_at, updated_at, version, applied_value
`

type MarkChangeRequestItemAppliedParams struct {
	AppliedAt              sql.NullString
	AppliedValue           sql.NullString
	AppliedResourceKind    sql.NullString
	AppliedResourceID      sql.NullInt64
	AppliedResourceVersion sql.NullInt64
	ID                     int64
	Version                int64
}

// Stamps the resource an approved item produced. `applied_at IS NULL` in the
// WHERE clause is what makes apply exactly-once: a replay updates no row, and
// the caller returns the already-recorded outcome instead of applying twice.
//
// applied_value is what reached the record, which since ADR-0014 need not be
// what the member proposed. Always pass it, using the empty string for the
// operations that set no value: NULL in this column means "applied before the
// portal recorded this" and must keep meaning only that (migration 0016).
func (q *Queries) MarkChangeRequestItemApplied(ctx context.Context, arg MarkChangeRequestItemAppliedParams) (MemberChangeRequestItem, error) {
	row := q.db.QueryRowContext(ctx, markChangeRequestItemApplied,
		arg.AppliedAt,
		arg.AppliedValue,
		arg.AppliedResourceKind,
		arg.AppliedResourceID,
		arg.AppliedResourceVersion,
		arg.ID,
		arg.Version,
	)
	var i MemberChangeRequestItem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Ordinal,
		&i.Operation,
		&i.ProposedValue,
		&i.TargetKind,
		&i.TargetID,
		&i.TargetVersion,
		&i.Sensitivity,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.VerificationNote,
		&i.AppliedAt,
		&i.AppliedResourceKind,
		&i.AppliedResourceID,
		&i.AppliedResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AppliedValue,
	)
	return i, err
}

const setChangeRequestStatus = `-- name: SetChangeRequestStatus :one
UPDATE member_change_requests
   SET status = ?1,
       resolved_at = ?2,
       withdrawn_at = ?3,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?4
   AND version = ?5
RETURNING id, source, status, requester_user_id, target_person_id, supplied_name, supplied_call_sign, supplied_contact, stated_relationship, summary, received_by, submitted_at, triaged_by, triaged_at, resolved_at, withdrawn_at, source_ip_hash, created_at, updated_at, version
`

type SetChangeRequestStatusParams struct {
	Status      string
	ResolvedAt  sql.NullString
	WithdrawnAt sql.NullString
	ID          int64
	Version     int64
}

func (q *Queries) SetChangeRequestStatus(ctx context.Context, arg SetChangeRequestStatusParams) (MemberChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, setChangeRequestStatus,
		arg.Status,
		arg.ResolvedAt,
		arg.WithdrawnAt,
		arg.ID,
		arg.Version,
	)
	var i MemberChangeRequest
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.RequesterUserID,
		&i.TargetPersonID,
		&i.SuppliedName,
		&i.SuppliedCallSign,
		&i.SuppliedContact,
		&i.StatedRelationship,
		&i.Summary,
		&i.ReceivedBy,
		&i.SubmittedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ResolvedAt,
		&i.WithdrawnAt,
		&i.SourceIpHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const setChangeRequestTarget = `-- name: SetChangeRequestTarget :one
UPDATE member_change_requests
   SET target_person_id = ?1,
       triaged_by = ?2,
       triaged_at = ?3,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?4
   AND version = ?5
RETURNING id, source, status, requester_user_id, target_person_id, supplied_name, supplied_call_sign, supplied_contact, stated_relationship, summary, received_by, submitted_at, triaged_by, triaged_at, resolved_at, withdrawn_at, source_ip_hash, created_at, updated_at, version
`

type SetChangeRequestTargetParams struct {
	TargetPersonID sql.NullInt64
	TriagedBy      sql.NullInt64
	TriagedAt      sql.NullString
	ID             int64
	Version        int64
}

// Officer triage links a supplied hint to a canonical person. The supplied_*
// snapshot is untouched: what the submitter said stays on the record.
func (q *Queries) SetChangeRequestTarget(ctx context.Context, arg SetChangeRequestTargetParams) (MemberChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, setChangeRequestTarget,
		arg.TargetPersonID,
		arg.TriagedBy,
		arg.TriagedAt,
		arg.ID,
		arg.Version,
	)
	var i MemberChangeRequest
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.RequesterUserID,
		&i.TargetPersonID,
		&i.SuppliedName,
		&i.SuppliedCallSign,
		&i.SuppliedContact,
		&i.StatedRelationship,
		&i.Summary,
		&i.ReceivedBy,
		&i.SubmittedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ResolvedAt,
		&i.WithdrawnAt,
		&i.SourceIpHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
