// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contact_methods.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archiveContactMethod = `-- name: ArchiveContactMethod :exec
UPDATE contact_methods
SET archived_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
`

type ArchiveContactMethodParams struct {
	ID      int64
	Version int64
}

func (q *Queries) ArchiveContactMethod(ctx context.Context, arg ArchiveContactMethodParams) error {
	_, err := q.db.ExecContext(ctx, archiveContactMethod, arg.ID, arg.Version)
	return err
}

const clearPrimaryForPerson = `-- name: ClearPrimaryForPerson :exec
UPDATE contact_methods
SET is_primary = 0,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE person_id = ? AND is_primary = 1 AND archived_at IS NULL
`

func (q *Queries) ClearPrimaryForPerson(ctx context.Context, personID int64) error {
	_, err := q.db.ExecContext(ctx, clearPrimaryForPerson, personID)
	return err
}

const createContactMethod = `-- name: CreateContactMethod :one
INSERT INTO contact_methods (person_id, kind, label, value_raw, value_norm, is_primary,
    postal_line1, postal_line2, postal_city, postal_state, postal_postal_code, postal_country)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, person_id, kind, label, value_raw, value_norm, is_primary, archived_at, postal_line1, postal_line2, postal_city, postal_state, postal_postal_code, postal_country, created_at, updated_at, version
`

type CreateContactMethodParams struct {
	PersonID         int64
	Kind             string
	Label            sql.NullString
	ValueRaw         string
	ValueNorm        string
	IsPrimary        int64
	PostalLine1      sql.NullString
	PostalLine2      sql.NullString
	PostalCity       sql.NullString
	PostalState      sql.NullString
	PostalPostalCode sql.NullString
	PostalCountry    sql.NullString
}

func (q *Queries) CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (ContactMethod, error) {
	row := q.db.QueryRowContext(ctx, createContactMethod,
		arg.PersonID,
		arg.Kind,
		arg.Label,
		arg.ValueRaw,
		arg.ValueNorm,
		arg.IsPrimary,
		arg.PostalLine1,
		arg.PostalLine2,
		arg.PostalCity,
		arg.PostalState,
		arg.PostalPostalCode,
		arg.PostalCountry,
	)
	var i ContactMethod
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Kind,
		&i.Label,
		&i.ValueRaw,
		&i.ValueNorm,
		&i.IsPrimary,
		&i.ArchivedAt,
		&i.PostalLine1,
		&i.PostalLine2,
		&i.PostalCity,
		&i.PostalState,
		&i.PostalPostalCode,
		&i.PostalCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const findContactMethodByNorm = `-- name: FindContactMethodByNorm :many
SELECT id, person_id, kind, label, value_raw, value_norm, is_primary, archived_at, postal_line1, postal_line2, postal_city, postal_state, postal_postal_code, postal_country, created_at, updated_at, version FROM contact_methods
WHERE kind = ? AND value_norm = ? AND archived_at IS NULL
`

type FindContactMethodByNormParams struct {
	Kind      string
	ValueNorm string
}

func (q *Queries) FindContactMethodByNorm(ctx context.Context, arg FindContactMethodByNormParams) ([]ContactMethod, error) {
	rows, err := q.db.QueryContext(ctx, findContactMethodByNorm, arg.Kind, arg.ValueNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactMethod{}
	for rows.Next() {
		var i ContactMethod
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Kind,
			&i.Label,
			&i.ValueRaw,
			&i.ValueNorm,
			&i.IsPrimary,
			&i.ArchivedAt,
			&i.PostalLine1,
			&i.PostalLine2,
			&i.PostalCity,
			&i.PostalState,
			&i.PostalPostalCode,
			&i.PostalCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactMethod = `-- name: GetContactMethod :one
SELECT id, person_id, kind, label, value_raw, value_norm, is_primary, archived_at, postal_line1, postal_line2, postal_city, postal_state, postal_postal_code, postal_country, created_at, updated_at, version FROM contact_methods WHERE id = ?
`

func (q *Queries) GetContactMethod(ctx context.Context, id int64) (ContactMethod, error) {
	row := q.db.QueryRowContext(ctx, getContactMethod, id)
	var i ContactMethod
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Kind,
		&i.Label,
		&i.ValueRaw,
		&i.ValueNorm,
		&i.IsPrimary,
		&i.ArchivedAt,
		&i.PostalLine1,
		&i.PostalLine2,
		&i.PostalCity,
		&i.PostalState,
		&i.PostalPostalCode,
		&i.PostalCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listContactMethods = `-- name: ListContactMethods :many
SELECT id, person_id, kind, label, value_raw, value_norm, is_primary, archived_at, postal_line1, postal_line2, postal_city, postal_state, postal_postal_code, postal_country, created_at, updated_at, version FROM contact_methods
WHERE person_id = ? AND archived_at IS NULL
ORDER BY is_primary DESC, kind, id
`

func (q *Queries) ListContactMethods(ctx context.Context, personID int64) ([]ContactMethod, error) {
	rows, err := q.db.QueryContext(ctx, listContactMethods, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactMethod{}
	for rows.Next() {
		var i ContactMethod
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Kind,
			&i.Label,
			&i.ValueRaw,
			&i.ValueNorm,
			&i.IsPrimary,
			&i.ArchivedAt,
			&i.PostalLine1,
			&i.PostalLine2,
			&i.PostalCity,
			&i.PostalState,
			&i.PostalPostalCode,
			&i.PostalCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimary = `-- name: SetPrimary :exec
UPDATE contact_methods
SET is_primary = 1,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) SetPrimary(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setPrimary, id)
	return err
}

const updateContactMethod = `-- name: UpdateContactMethod :one
UPDATE contact_methods
SET label = ?, value_raw = ?, value_norm = ?,
    postal_line1 = ?, postal_line2 = ?, postal_city = ?,
    postal_state = ?, postal_postal_code = ?, postal_country = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, person_id, kind, label, value_raw, value_norm, is_primary, archived_at, postal_line1, postal_line2, postal_city, postal_state, postal_postal_code, postal_country, created_at, updated_at, version
`

type UpdateContactMethodParams struct {
	Label            sql.NullString
	ValueRaw         string
	ValueNorm        string
	PostalLine1      sql.NullString
	PostalLine2      sql.NullString
	PostalCity       sql.NullString
	PostalState      sql.NullString
	PostalPostalCode sql.NullString
	PostalCountry    sql.NullString
	ID               int64
	Version          int64
}

func (q *Queries) UpdateContactMethod(ctx context.Context, arg UpdateContactMethodParams) (ContactMethod, error) {
	row := q.db.QueryRowContext(ctx, updateContactMethod,
		arg.Label,
		arg.ValueRaw,
		arg.ValueNorm,
		arg.PostalLine1,
		arg.PostalLine2,
		arg.PostalCity,
		arg.PostalState,
		arg.PostalPostalCode,
		arg.PostalCountry,
		arg.ID,
		arg.Version,
	)
	var i ContactMethod
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Kind,
		&i.Label,
		&i.ValueRaw,
		&i.ValueNorm,
		&i.IsPrimary,
		&i.ArchivedAt,
		&i.PostalLine1,
		&i.PostalLine2,
		&i.PostalCity,
		&i.PostalState,
		&i.PostalPostalCode,
		&i.PostalCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
