// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corrections.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getBatchLedgerTotals = `-- name: GetBatchLedgerTotals :one


SELECT
    CAST(COUNT(*) AS INTEGER)                                                                  AS payment_count,
    CAST(COALESCE(SUM(amount_cents), 0) AS INTEGER)                                            AS net_total_cents,
    CAST(COALESCE(SUM(CASE WHEN method = 'cash'  THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS cash_total_cents,
    CAST(COALESCE(SUM(CASE WHEN method = 'check' THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS check_total_cents,
    CAST(COALESCE(SUM(CASE WHEN method = 'other' THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS other_total_cents
FROM payments
WHERE batch_id = ?
`

type GetBatchLedgerTotalsRow struct {
	PaymentCount    int64
	NetTotalCents   int64
	CashTotalCents  int64
	CheckTotalCents int64
	OtherTotalCents int64
}

// Posted-payment corrections.
//
// Nothing here updates or deletes a payment. A correction appends a signed
// reversal and a positive replacement and links the three together, so the
// original stays exactly as it was recorded.
// Walking a chain forward uses GetPaymentCorrectionByOriginal from
// treasury.sql: the correction that superseded a payment is the one whose
// original_payment_id is that payment.
// Net totals over the posted ledger rather than the frozen draft entries. After
// a correction the two legitimately differ: the entries record what was typed,
// the ledger records what the club actually holds.
func (q *Queries) GetBatchLedgerTotals(ctx context.Context, batchID sql.NullInt64) (GetBatchLedgerTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getBatchLedgerTotals, batchID)
	var i GetBatchLedgerTotalsRow
	err := row.Scan(
		&i.PaymentCount,
		&i.NetTotalCents,
		&i.CashTotalCents,
		&i.CheckTotalCents,
		&i.OtherTotalCents,
	)
	return i, err
}

const getCoverageEventByPayment = `-- name: GetCoverageEventByPayment :one
SELECT id, membership_id, paid_through, reason_kind, reason, payment_id, import_run_id, supersedes_event_id, source_note, decided_by, decided_at, created_at FROM coverage_events
WHERE payment_id = ?
ORDER BY id DESC
LIMIT 1
`

// The coverage decision a given payment granted, if it granted one.
func (q *Queries) GetCoverageEventByPayment(ctx context.Context, paymentID sql.NullInt64) (CoverageEvent, error) {
	row := q.db.QueryRowContext(ctx, getCoverageEventByPayment, paymentID)
	var i CoverageEvent
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.PaidThrough,
		&i.ReasonKind,
		&i.Reason,
		&i.PaymentID,
		&i.ImportRunID,
		&i.SupersedesEventID,
		&i.SourceNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}
