// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countDirectoryEligibleGrants = `-- name: CountDirectoryEligibleGrants :one

SELECT count(*)
  FROM member_access_grants g
  JOIN memberships m ON m.person_id = g.person_id
 WHERE g.user_id = ?
   AND g.revoked_at IS NULL
   AND m.base_type = 'full'
   AND m.lifecycle = 'approved'
   AND m.ended_on IS NULL
`

// The member directory (bcars-portal-4ux.7).
//
// Contact values are filtered HERE, in SQL, not in a service or a template. A
// value the caller may not see is never selected, so it cannot be leaked by a
// DTO field someone forgets to strip, a template that renders the wrong
// variable, or a debug log. The Phase 2 audit found a treasury page reachable
// only because nothing consumed the link it stored; the same class of mistake
// with a hidden phone number would be a privacy breach rather than an
// inconvenience.
//
// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
// offset, so a multi-byte character above a query corrupts the SQL it parses.
//
// The caller's eligibility probe: does this user hold an active grant to a
// person whose membership is an active approved FULL membership.
//
// Associates may hold grants and use their own profile, but may not browse the
// directory. Eligibility is deliberately a separate question from holding the
// directory.read capability, which is why the capability alone never answers
// it.
func (q *Queries) CountDirectoryEligibleGrants(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDirectoryEligibleGrants, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDirectoryEntries = `-- name: CountDirectoryEntries :one
SELECT count(*)
  FROM persons p
  JOIN memberships m ON m.person_id = p.id
 WHERE m.lifecycle = 'approved'
   AND m.ended_on IS NULL
   AND m.base_type IN ('full', 'associate')
   AND p.deactivated_at IS NULL
   AND p.deceased_at IS NULL
   AND (?1 IS NULL
        OR p.display_name LIKE '%' || ?1 || '%'
        OR p.call_sign LIKE '%' || ?1 || '%')
`

// The same population as ListDirectoryEntries, for pagination. It deliberately
// shares the eligibility predicate and NOT the contact filtering, because a
// total must not depend on what the caller may see.
func (q *Queries) CountDirectoryEntries(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDirectoryEntries, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDirectoryEntries = `-- name: ListDirectoryEntries :many
SELECT p.id                                     AS person_id,
       p.display_name                           AS display_name,
       p.call_sign                              AS call_sign,
       m.base_type                              AS base_type,
       CAST(COALESCE((SELECT cm.value_raw
          FROM contact_methods cm
         WHERE cm.person_id = p.id
           AND cm.kind = 'email'
           AND cm.archived_at IS NULL
           AND CASE
                 WHEN (SELECT ev.audience
                         FROM contact_method_visibility_events ev
                        WHERE ev.contact_method_id = cm.id
                        ORDER BY ev.effective_at DESC, ev.id DESC
                        LIMIT 1) IS NULL
                 THEN m.base_type = 'full'
                 ELSE (SELECT ev.audience
                         FROM contact_method_visibility_events ev
                        WHERE ev.contact_method_id = cm.id
                        ORDER BY ev.effective_at DESC, ev.id DESC
                        LIMIT 1) = 'full_members'
               END
         ORDER BY cm.is_primary DESC, cm.id
         LIMIT 1), '') AS TEXT)                 AS email,
       CAST(COALESCE((SELECT cm.value_raw
          FROM contact_methods cm
         WHERE cm.person_id = p.id
           AND cm.kind = 'phone'
           AND cm.archived_at IS NULL
           AND CASE
                 WHEN (SELECT ev.audience
                         FROM contact_method_visibility_events ev
                        WHERE ev.contact_method_id = cm.id
                        ORDER BY ev.effective_at DESC, ev.id DESC
                        LIMIT 1) IS NULL
                 THEN m.base_type = 'full'
                 ELSE (SELECT ev.audience
                         FROM contact_method_visibility_events ev
                        WHERE ev.contact_method_id = cm.id
                        ORDER BY ev.effective_at DESC, ev.id DESC
                        LIMIT 1) = 'full_members'
               END
         ORDER BY cm.is_primary DESC, cm.id
         LIMIT 1), '') AS TEXT)                 AS phone
  FROM persons p
  JOIN memberships m ON m.person_id = p.id
 WHERE m.lifecycle = 'approved'
   AND m.ended_on IS NULL
   AND m.base_type IN ('full', 'associate')
   AND p.deactivated_at IS NULL
   AND p.deceased_at IS NULL
   AND (?1 IS NULL
        OR p.display_name LIKE '%' || ?1 || '%'
        OR p.call_sign LIKE '%' || ?1 || '%')
 ORDER BY p.sort_name, p.id
 LIMIT ?3 OFFSET ?2
`

type ListDirectoryEntriesParams struct {
	Search     interface{}
	PageOffset int64
	PageLimit  int64
}

type ListDirectoryEntriesRow struct {
	PersonID    int64
	DisplayName string
	CallSign    sql.NullString
	BaseType    string
	Email       string
	Phone       string
}

// Rows are active approved Full and Associate members.
//
// An email or phone survives only when the latest visibility decision for that
// contact permits full_members. With no decision on file the row falls back to
// the Phase 1 domain default: a Full member's contact is shareable with Full
// members, an Associate's is not. An imported `import_default` event is a
// recorded decision like any other, so it keeps its result until an officer
// supersedes it.
//
// A withheld value and an absent one both come back as the empty string. That
// is deliberate: one representation means a caller cannot distinguish "this
// member hid their number" from "this member has no number on file", which is
// exactly the non-disclosure the design asks for.
//
// Ordering is by sort_name then person id. The id tie-breaker is what keeps a
// page boundary from shifting between calls when two members sort equally, so
// paging cannot silently skip someone.
func (q *Queries) ListDirectoryEntries(ctx context.Context, arg ListDirectoryEntriesParams) ([]ListDirectoryEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectoryEntries, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectoryEntriesRow{}
	for rows.Next() {
		var i ListDirectoryEntriesRow
		if err := rows.Scan(
			&i.PersonID,
			&i.DisplayName,
			&i.CallSign,
			&i.BaseType,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
