// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const commitImportRun = `-- name: CommitImportRun :one
UPDATE import_runs
SET status = 'committed',
    committed_by = ?,
    committed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    result_summary_json = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key, committed_by, committed_at, result_summary_json, created_at, updated_at, version
`

type CommitImportRunParams struct {
	CommittedBy       sql.NullInt64
	ResultSummaryJson sql.NullString
	ID                int64
	Version           int64
}

func (q *Queries) CommitImportRun(ctx context.Context, arg CommitImportRunParams) (ImportRun, error) {
	row := q.db.QueryRowContext(ctx, commitImportRun,
		arg.CommittedBy,
		arg.ResultSummaryJson,
		arg.ID,
		arg.Version,
	)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CommittedBy,
		&i.CommittedAt,
		&i.ResultSummaryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const countStagedRowsByAction = `-- name: CountStagedRowsByAction :many
SELECT proposed_action, count(*) as cnt FROM staged_import_rows
WHERE import_run_id = ?
GROUP BY proposed_action
`

type CountStagedRowsByActionRow struct {
	ProposedAction string
	Cnt            int64
}

func (q *Queries) CountStagedRowsByAction(ctx context.Context, importRunID int64) ([]CountStagedRowsByActionRow, error) {
	rows, err := q.db.QueryContext(ctx, countStagedRowsByAction, importRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountStagedRowsByActionRow{}
	for rows.Next() {
		var i CountStagedRowsByActionRow
		if err := rows.Scan(&i.ProposedAction, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnresolvedManualRows = `-- name: CountUnresolvedManualRows :one
SELECT count(*) FROM staged_import_rows
WHERE import_run_id = ? AND requires_manual = 1
AND id NOT IN (
    SELECT DISTINCT staged_import_row_id FROM reconciliation_decisions
)
`

func (q *Queries) CountUnresolvedManualRows(ctx context.Context, importRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnresolvedManualRows, importRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalID = `-- name: CreateExternalID :one
INSERT INTO external_ids (entity_kind, entity_id, system, external_id)
VALUES (?, ?, ?, ?)
RETURNING id, entity_kind, entity_id, system, external_id, created_at
`

type CreateExternalIDParams struct {
	EntityKind string
	EntityID   int64
	System     string
	ExternalID string
}

func (q *Queries) CreateExternalID(ctx context.Context, arg CreateExternalIDParams) (ExternalID, error) {
	row := q.db.QueryRowContext(ctx, createExternalID,
		arg.EntityKind,
		arg.EntityID,
		arg.System,
		arg.ExternalID,
	)
	var i ExternalID
	err := row.Scan(
		&i.ID,
		&i.EntityKind,
		&i.EntityID,
		&i.System,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const createImportRun = `-- name: CreateImportRun :one
INSERT INTO import_runs (source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key)
VALUES (?, ?, ?, ?, ?, 'uploaded', ?)
RETURNING id, source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key, committed_by, committed_at, result_summary_json, created_at, updated_at, version
`

type CreateImportRunParams struct {
	SourceKind     string
	SourceFilename string
	SourceSha256   string
	UploadedBy     int64
	UploadedAt     string
	IdempotencyKey string
}

func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error) {
	row := q.db.QueryRowContext(ctx, createImportRun,
		arg.SourceKind,
		arg.SourceFilename,
		arg.SourceSha256,
		arg.UploadedBy,
		arg.UploadedAt,
		arg.IdempotencyKey,
	)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CommittedBy,
		&i.CommittedAt,
		&i.ResultSummaryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createReconciliationDecision = `-- name: CreateReconciliationDecision :one
INSERT INTO reconciliation_decisions (staged_import_row_id, decided_by, decided_at, action, payload_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, staged_import_row_id, decided_by, decided_at, "action", payload_json, created_at
`

type CreateReconciliationDecisionParams struct {
	StagedImportRowID int64
	DecidedBy         int64
	DecidedAt         string
	Action            string
	PayloadJson       sql.NullString
}

func (q *Queries) CreateReconciliationDecision(ctx context.Context, arg CreateReconciliationDecisionParams) (ReconciliationDecision, error) {
	row := q.db.QueryRowContext(ctx, createReconciliationDecision,
		arg.StagedImportRowID,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.Action,
		arg.PayloadJson,
	)
	var i ReconciliationDecision
	err := row.Scan(
		&i.ID,
		&i.StagedImportRowID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Action,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const createStagedRow = `-- name: CreateStagedRow :one
INSERT INTO staged_import_rows (import_run_id, source_row_index, source_external_id, raw_json, normalized_json, match_person_id, match_method, proposed_action, proposed_changes_json, validation_errors_json, requires_manual, manual_reason)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, import_run_id, source_row_index, source_external_id, raw_json, normalized_json, match_person_id, match_method, proposed_action, proposed_changes_json, validation_errors_json, requires_manual, manual_reason, created_at
`

type CreateStagedRowParams struct {
	ImportRunID          int64
	SourceRowIndex       int64
	SourceExternalID     sql.NullString
	RawJson              string
	NormalizedJson       string
	MatchPersonID        sql.NullInt64
	MatchMethod          sql.NullString
	ProposedAction       string
	ProposedChangesJson  sql.NullString
	ValidationErrorsJson sql.NullString
	RequiresManual       int64
	ManualReason         sql.NullString
}

func (q *Queries) CreateStagedRow(ctx context.Context, arg CreateStagedRowParams) (StagedImportRow, error) {
	row := q.db.QueryRowContext(ctx, createStagedRow,
		arg.ImportRunID,
		arg.SourceRowIndex,
		arg.SourceExternalID,
		arg.RawJson,
		arg.NormalizedJson,
		arg.MatchPersonID,
		arg.MatchMethod,
		arg.ProposedAction,
		arg.ProposedChangesJson,
		arg.ValidationErrorsJson,
		arg.RequiresManual,
		arg.ManualReason,
	)
	var i StagedImportRow
	err := row.Scan(
		&i.ID,
		&i.ImportRunID,
		&i.SourceRowIndex,
		&i.SourceExternalID,
		&i.RawJson,
		&i.NormalizedJson,
		&i.MatchPersonID,
		&i.MatchMethod,
		&i.ProposedAction,
		&i.ProposedChangesJson,
		&i.ValidationErrorsJson,
		&i.RequiresManual,
		&i.ManualReason,
		&i.CreatedAt,
	)
	return i, err
}

const findExternalID = `-- name: FindExternalID :one
SELECT id, entity_kind, entity_id, system, external_id, created_at FROM external_ids WHERE system = ? AND external_id = ?
`

type FindExternalIDParams struct {
	System     string
	ExternalID string
}

func (q *Queries) FindExternalID(ctx context.Context, arg FindExternalIDParams) (ExternalID, error) {
	row := q.db.QueryRowContext(ctx, findExternalID, arg.System, arg.ExternalID)
	var i ExternalID
	err := row.Scan(
		&i.ID,
		&i.EntityKind,
		&i.EntityID,
		&i.System,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const findImportCoverageEvent = `-- name: FindImportCoverageEvent :one
SELECT id, membership_id, paid_through, reason_kind, reason, payment_id, import_run_id, supersedes_event_id, source_note, decided_by, decided_at, created_at FROM coverage_events
WHERE membership_id = ? AND paid_through = ? AND reason_kind = 'import'
ORDER BY id DESC
LIMIT 1
`

type FindImportCoverageEventParams struct {
	MembershipID int64
	PaidThrough  string
}

// Guards the import cutover against re-importing the same paid-through value:
// a second import of unchanged data must not append a duplicate decision.
func (q *Queries) FindImportCoverageEvent(ctx context.Context, arg FindImportCoverageEventParams) (CoverageEvent, error) {
	row := q.db.QueryRowContext(ctx, findImportCoverageEvent, arg.MembershipID, arg.PaidThrough)
	var i CoverageEvent
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.PaidThrough,
		&i.ReasonKind,
		&i.Reason,
		&i.PaymentID,
		&i.ImportRunID,
		&i.SupersedesEventID,
		&i.SourceNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getImportRun = `-- name: GetImportRun :one
SELECT id, source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key, committed_by, committed_at, result_summary_json, created_at, updated_at, version FROM import_runs WHERE id = ?
`

func (q *Queries) GetImportRun(ctx context.Context, id int64) (ImportRun, error) {
	row := q.db.QueryRowContext(ctx, getImportRun, id)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CommittedBy,
		&i.CommittedAt,
		&i.ResultSummaryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getImportRunByIdempotencyKey = `-- name: GetImportRunByIdempotencyKey :one
SELECT id, source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key, committed_by, committed_at, result_summary_json, created_at, updated_at, version FROM import_runs WHERE idempotency_key = ?
`

func (q *Queries) GetImportRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ImportRun, error) {
	row := q.db.QueryRowContext(ctx, getImportRunByIdempotencyKey, idempotencyKey)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CommittedBy,
		&i.CommittedAt,
		&i.ResultSummaryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getStagedRow = `-- name: GetStagedRow :one
SELECT id, import_run_id, source_row_index, source_external_id, raw_json, normalized_json, match_person_id, match_method, proposed_action, proposed_changes_json, validation_errors_json, requires_manual, manual_reason, created_at FROM staged_import_rows WHERE id = ?
`

func (q *Queries) GetStagedRow(ctx context.Context, id int64) (StagedImportRow, error) {
	row := q.db.QueryRowContext(ctx, getStagedRow, id)
	var i StagedImportRow
	err := row.Scan(
		&i.ID,
		&i.ImportRunID,
		&i.SourceRowIndex,
		&i.SourceExternalID,
		&i.RawJson,
		&i.NormalizedJson,
		&i.MatchPersonID,
		&i.MatchMethod,
		&i.ProposedAction,
		&i.ProposedChangesJson,
		&i.ValidationErrorsJson,
		&i.RequiresManual,
		&i.ManualReason,
		&i.CreatedAt,
	)
	return i, err
}

const listDecisionsForRow = `-- name: ListDecisionsForRow :many
SELECT id, staged_import_row_id, decided_by, decided_at, "action", payload_json, created_at FROM reconciliation_decisions
WHERE staged_import_row_id = ?
ORDER BY decided_at
`

func (q *Queries) ListDecisionsForRow(ctx context.Context, stagedImportRowID int64) ([]ReconciliationDecision, error) {
	rows, err := q.db.QueryContext(ctx, listDecisionsForRow, stagedImportRowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationDecision{}
	for rows.Next() {
		var i ReconciliationDecision
		if err := rows.Scan(
			&i.ID,
			&i.StagedImportRowID,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Action,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalIDsForEntity = `-- name: ListExternalIDsForEntity :many
SELECT id, entity_kind, entity_id, system, external_id, created_at FROM external_ids WHERE entity_kind = ? AND entity_id = ?
`

type ListExternalIDsForEntityParams struct {
	EntityKind string
	EntityID   int64
}

func (q *Queries) ListExternalIDsForEntity(ctx context.Context, arg ListExternalIDsForEntityParams) ([]ExternalID, error) {
	rows, err := q.db.QueryContext(ctx, listExternalIDsForEntity, arg.EntityKind, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalID{}
	for rows.Next() {
		var i ExternalID
		if err := rows.Scan(
			&i.ID,
			&i.EntityKind,
			&i.EntityID,
			&i.System,
			&i.ExternalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRuns = `-- name: ListImportRuns :many
SELECT id, source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key, committed_by, committed_at, result_summary_json, created_at, updated_at, version FROM import_runs ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListImportRunsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListImportRuns(ctx context.Context, arg ListImportRunsParams) ([]ImportRun, error) {
	rows, err := q.db.QueryContext(ctx, listImportRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportRun{}
	for rows.Next() {
		var i ImportRun
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.SourceFilename,
			&i.SourceSha256,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.Status,
			&i.IdempotencyKey,
			&i.CommittedBy,
			&i.CommittedAt,
			&i.ResultSummaryJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedRows = `-- name: ListStagedRows :many
SELECT id, import_run_id, source_row_index, source_external_id, raw_json, normalized_json, match_person_id, match_method, proposed_action, proposed_changes_json, validation_errors_json, requires_manual, manual_reason, created_at FROM staged_import_rows
WHERE import_run_id = ?
ORDER BY source_row_index
LIMIT ? OFFSET ?
`

type ListStagedRowsParams struct {
	ImportRunID int64
	Limit       int64
	Offset      int64
}

func (q *Queries) ListStagedRows(ctx context.Context, arg ListStagedRowsParams) ([]StagedImportRow, error) {
	rows, err := q.db.QueryContext(ctx, listStagedRows, arg.ImportRunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StagedImportRow{}
	for rows.Next() {
		var i StagedImportRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportRunID,
			&i.SourceRowIndex,
			&i.SourceExternalID,
			&i.RawJson,
			&i.NormalizedJson,
			&i.MatchPersonID,
			&i.MatchMethod,
			&i.ProposedAction,
			&i.ProposedChangesJson,
			&i.ValidationErrorsJson,
			&i.RequiresManual,
			&i.ManualReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedRowsRequiringManual = `-- name: ListStagedRowsRequiringManual :many
SELECT id, import_run_id, source_row_index, source_external_id, raw_json, normalized_json, match_person_id, match_method, proposed_action, proposed_changes_json, validation_errors_json, requires_manual, manual_reason, created_at FROM staged_import_rows
WHERE import_run_id = ? AND requires_manual = 1
ORDER BY source_row_index
LIMIT ? OFFSET ?
`

type ListStagedRowsRequiringManualParams struct {
	ImportRunID int64
	Limit       int64
	Offset      int64
}

func (q *Queries) ListStagedRowsRequiringManual(ctx context.Context, arg ListStagedRowsRequiringManualParams) ([]StagedImportRow, error) {
	rows, err := q.db.QueryContext(ctx, listStagedRowsRequiringManual, arg.ImportRunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StagedImportRow{}
	for rows.Next() {
		var i StagedImportRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportRunID,
			&i.SourceRowIndex,
			&i.SourceExternalID,
			&i.RawJson,
			&i.NormalizedJson,
			&i.MatchPersonID,
			&i.MatchMethod,
			&i.ProposedAction,
			&i.ProposedChangesJson,
			&i.ValidationErrorsJson,
			&i.RequiresManual,
			&i.ManualReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportRunStatus = `-- name: UpdateImportRunStatus :one
UPDATE import_runs
SET status = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, source_kind, source_filename, source_sha256, uploaded_by, uploaded_at, status, idempotency_key, committed_by, committed_at, result_summary_json, created_at, updated_at, version
`

type UpdateImportRunStatusParams struct {
	Status  string
	ID      int64
	Version int64
}

func (q *Queries) UpdateImportRunStatus(ctx context.Context, arg UpdateImportRunStatusParams) (ImportRun, error) {
	row := q.db.QueryRowContext(ctx, updateImportRunStatus, arg.Status, arg.ID, arg.Version)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceFilename,
		&i.SourceSha256,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CommittedBy,
		&i.CommittedAt,
		&i.ResultSummaryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateStagedRowAction = `-- name: UpdateStagedRowAction :one
UPDATE staged_import_rows
SET proposed_action = ?, requires_manual = ?, manual_reason = ?
WHERE id = ?
RETURNING id, import_run_id, source_row_index, source_external_id, raw_json, normalized_json, match_person_id, match_method, proposed_action, proposed_changes_json, validation_errors_json, requires_manual, manual_reason, created_at
`

type UpdateStagedRowActionParams struct {
	ProposedAction string
	RequiresManual int64
	ManualReason   sql.NullString
	ID             int64
}

func (q *Queries) UpdateStagedRowAction(ctx context.Context, arg UpdateStagedRowActionParams) (StagedImportRow, error) {
	row := q.db.QueryRowContext(ctx, updateStagedRowAction,
		arg.ProposedAction,
		arg.RequiresManual,
		arg.ManualReason,
		arg.ID,
	)
	var i StagedImportRow
	err := row.Scan(
		&i.ID,
		&i.ImportRunID,
		&i.SourceRowIndex,
		&i.SourceExternalID,
		&i.RawJson,
		&i.NormalizedJson,
		&i.MatchPersonID,
		&i.MatchMethod,
		&i.ProposedAction,
		&i.ProposedChangesJson,
		&i.ValidationErrorsJson,
		&i.RequiresManual,
		&i.ManualReason,
		&i.CreatedAt,
	)
	return i, err
}
