// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member_profile.sql

package sqlcgen

import (
	"context"
)

const getGrantedProfile = `-- name: GetGrantedProfile :one
SELECT p.id                                        AS person_id,
       p.display_name                              AS display_name,
       COALESCE(p.call_sign, '')                   AS call_sign,
       p.version                                   AS person_version,
       g.access_kind                               AS access_kind,
       CAST(COALESCE(m.id, 0) AS INTEGER)          AS membership_id,
       CAST(COALESCE(m.base_type, '') AS TEXT)     AS base_type,
       CAST(COALESCE(m.lifecycle, '') AS TEXT)     AS lifecycle
  FROM member_access_grants g
  JOIN persons p ON p.id = g.person_id
  LEFT JOIN memberships m ON m.person_id = p.id
 WHERE g.user_id = ?1
   AND g.person_id = ?2
   AND g.revoked_at IS NULL
 LIMIT 1
`

type GetGrantedProfileParams struct {
	UserID   int64
	PersonID int64
}

type GetGrantedProfileRow struct {
	PersonID      int64
	DisplayName   string
	CallSign      string
	PersonVersion int64
	AccessKind    string
	MembershipID  int64
	BaseType      string
	Lifecycle     string
}

// One record, by person, for this caller. Returns no row when the grant is
// missing or revoked, which callers translate to the same 404 an unknown
// person produces.
// person_version travels with the record so a correction can say which version
// of it the member was looking at. A contact method already carries its own
// version for that reason; without this the name and call-sign fields of the
// member's edit form had nothing to carry, and an approval weeks later could
// silently overwrite an officer's more recent edit.
func (q *Queries) GetGrantedProfile(ctx context.Context, arg GetGrantedProfileParams) (GetGrantedProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getGrantedProfile, arg.UserID, arg.PersonID)
	var i GetGrantedProfileRow
	err := row.Scan(
		&i.PersonID,
		&i.DisplayName,
		&i.CallSign,
		&i.PersonVersion,
		&i.AccessKind,
		&i.MembershipID,
		&i.BaseType,
		&i.Lifecycle,
	)
	return i, err
}

const listGrantedContactMethods = `-- name: ListGrantedContactMethods :many
SELECT c.id                              AS contact_method_id,
       c.kind                            AS kind,
       COALESCE(c.label, '')             AS label,
       c.value_raw                       AS value,
       c.is_primary                      AS is_primary,
       c.version                         AS version,
       CAST(COALESCE((
           SELECT v.audience
             FROM contact_method_visibility_events v
            WHERE v.contact_method_id = c.id
            ORDER BY v.effective_at DESC, v.id DESC
            LIMIT 1
       ), '') AS TEXT)                   AS shared_with
  FROM contact_methods c
  JOIN member_access_grants g
    ON g.person_id = c.person_id
   AND g.user_id = ?1
   AND g.revoked_at IS NULL
 WHERE c.person_id = ?2
   AND c.archived_at IS NULL
 ORDER BY c.kind, c.is_primary DESC, c.id
`

type ListGrantedContactMethodsParams struct {
	UserID   int64
	PersonID int64
}

type ListGrantedContactMethodsRow struct {
	ContactMethodID int64
	Kind            string
	Label           string
	Value           string
	IsPrimary       int64
	Version         int64
	SharedWith      string
}

// The caller's own contact methods on a granted record, with the sharing
// choice that currently applies to each.
//
// This is the member's OWN data, so unlike the directory it is not filtered by
// visibility: a member must see the phone number the club holds for them in
// order to notice it is wrong. The audience the latest visibility event chose
// is reported alongside, so the member can see what the club shares rather than
// having to ask. An empty shared_with means no decision is on file and the
// Phase 1 domain default applies.
//
// Archived methods are excluded. They are history, and offering them for
// correction would invite a member to fix a value nothing uses.
func (q *Queries) ListGrantedContactMethods(ctx context.Context, arg ListGrantedContactMethodsParams) ([]ListGrantedContactMethodsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantedContactMethods, arg.UserID, arg.PersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantedContactMethodsRow{}
	for rows.Next() {
		var i ListGrantedContactMethodsRow
		if err := rows.Scan(
			&i.ContactMethodID,
			&i.Kind,
			&i.Label,
			&i.Value,
			&i.IsPrimary,
			&i.Version,
			&i.SharedWith,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedProfiles = `-- name: ListGrantedProfiles :many

SELECT p.id                                        AS person_id,
       p.display_name                              AS display_name,
       COALESCE(p.call_sign, '')                   AS call_sign,
       g.access_kind                               AS access_kind,
       CAST(COALESCE(m.id, 0) AS INTEGER)          AS membership_id,
       CAST(COALESCE(m.base_type, '') AS TEXT)     AS base_type,
       CAST(COALESCE(m.lifecycle, '') AS TEXT)     AS lifecycle
  FROM member_access_grants g
  JOIN persons p ON p.id = g.person_id
  LEFT JOIN memberships m ON m.person_id = p.id
 WHERE g.user_id = ?1
   AND g.revoked_at IS NULL
 ORDER BY p.sort_name, p.id
`

type ListGrantedProfilesRow struct {
	PersonID     int64
	DisplayName  string
	CallSign     string
	AccessKind   string
	MembershipID int64
	BaseType     string
	Lifecycle    string
}

// Member self-service profile reads (bcars-portal-4ux.6).
//
// Every query here joins member_access_grants and requires an ACTIVE grant for
// the calling user. That join is the authorization, expressed where it cannot
// be forgotten: a record this caller was never granted is not filtered out of a
// result, it is never selected, so no DTO field, template variable, or log line
// downstream can carry it.
//
// These deliberately do NOT reuse the administrative person and membership
// reads. Those select officer-facing columns -- notes, audit fields, the whole
// row -- and a member must never receive them. The column lists below are the
// safe read model, and they are short on purpose.
//
// Every record the caller may currently see, one row per person. A person with
// no membership row still appears: the grant is to the PERSON, and a member
// whose membership record is missing must still be able to see and correct
// their own name rather than silently having no profile at all.
func (q *Queries) ListGrantedProfiles(ctx context.Context, userID int64) ([]ListGrantedProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantedProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantedProfilesRow{}
	for rows.Next() {
		var i ListGrantedProfilesRow
		if err := rows.Scan(
			&i.PersonID,
			&i.DisplayName,
			&i.CallSign,
			&i.AccessKind,
			&i.MembershipID,
			&i.BaseType,
			&i.Lifecycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
