// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: memberships.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const approveMembership = `-- name: ApproveMembership :one
UPDATE memberships
SET lifecycle = 'approved', base_type = ?, joined_on = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, person_id, base_type, lifecycle, joined_on, ended_on, legacy_current_until, legacy_current_until_note, created_at, updated_at, version
`

type ApproveMembershipParams struct {
	BaseType string
	JoinedOn sql.NullString
	ID       int64
	Version  int64
}

func (q *Queries) ApproveMembership(ctx context.Context, arg ApproveMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, approveMembership,
		arg.BaseType,
		arg.JoinedOn,
		arg.ID,
		arg.Version,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BaseType,
		&i.Lifecycle,
		&i.JoinedOn,
		&i.EndedOn,
		&i.LegacyCurrentUntil,
		&i.LegacyCurrentUntilNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createFCCVerification = `-- name: CreateFCCVerification :one
INSERT INTO fcc_verifications (membership_id, call_sign, license_class, verification_source, verified_by, verified_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, membership_id, call_sign, license_class, verification_source, verified_by, verified_at, expires_at, revoked_at, notes, created_at
`

type CreateFCCVerificationParams struct {
	MembershipID       int64
	CallSign           string
	LicenseClass       sql.NullString
	VerificationSource string
	VerifiedBy         int64
	VerifiedAt         string
}

func (q *Queries) CreateFCCVerification(ctx context.Context, arg CreateFCCVerificationParams) (FccVerification, error) {
	row := q.db.QueryRowContext(ctx, createFCCVerification,
		arg.MembershipID,
		arg.CallSign,
		arg.LicenseClass,
		arg.VerificationSource,
		arg.VerifiedBy,
		arg.VerifiedAt,
	)
	var i FccVerification
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.CallSign,
		&i.LicenseClass,
		&i.VerificationSource,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createHonoraryGrant = `-- name: CreateHonoraryGrant :one
INSERT INTO honorary_grants (membership_id, starts_on, ends_on, is_lifetime, reason, approved_by, approved_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, membership_id, starts_on, ends_on, is_lifetime, reason, approved_by, approved_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version
`

type CreateHonoraryGrantParams struct {
	MembershipID int64
	StartsOn     string
	EndsOn       sql.NullString
	IsLifetime   int64
	Reason       string
	ApprovedBy   int64
	ApprovedAt   string
}

func (q *Queries) CreateHonoraryGrant(ctx context.Context, arg CreateHonoraryGrantParams) (HonoraryGrant, error) {
	row := q.db.QueryRowContext(ctx, createHonoraryGrant,
		arg.MembershipID,
		arg.StartsOn,
		arg.EndsOn,
		arg.IsLifetime,
		arg.Reason,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i HonoraryGrant
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsLifetime,
		&i.Reason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (person_id, base_type, lifecycle)
VALUES (?, ?, 'pending')
RETURNING id, person_id, base_type, lifecycle, joined_on, ended_on, legacy_current_until, legacy_current_until_note, created_at, updated_at, version
`

type CreateMembershipParams struct {
	PersonID int64
	BaseType string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, createMembership, arg.PersonID, arg.BaseType)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BaseType,
		&i.Lifecycle,
		&i.JoinedOn,
		&i.EndedOn,
		&i.LegacyCurrentUntil,
		&i.LegacyCurrentUntilNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createMembershipApproval = `-- name: CreateMembershipApproval :one
INSERT INTO membership_approvals (membership_id, decision, approved_type, decided_by, decided_at, reason)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, membership_id, decision, approved_type, decided_by, decided_at, reason, created_at
`

type CreateMembershipApprovalParams struct {
	MembershipID int64
	Decision     string
	ApprovedType sql.NullString
	DecidedBy    int64
	DecidedAt    string
	Reason       sql.NullString
}

func (q *Queries) CreateMembershipApproval(ctx context.Context, arg CreateMembershipApprovalParams) (MembershipApproval, error) {
	row := q.db.QueryRowContext(ctx, createMembershipApproval,
		arg.MembershipID,
		arg.Decision,
		arg.ApprovedType,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.Reason,
	)
	var i MembershipApproval
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.Decision,
		&i.ApprovedType,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getFCCVerification = `-- name: GetFCCVerification :one
SELECT id, membership_id, call_sign, license_class, verification_source, verified_by, verified_at, expires_at, revoked_at, notes, created_at FROM fcc_verifications WHERE id = ?
`

func (q *Queries) GetFCCVerification(ctx context.Context, id int64) (FccVerification, error) {
	row := q.db.QueryRowContext(ctx, getFCCVerification, id)
	var i FccVerification
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.CallSign,
		&i.LicenseClass,
		&i.VerificationSource,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getHonoraryGrant = `-- name: GetHonoraryGrant :one
SELECT id, membership_id, starts_on, ends_on, is_lifetime, reason, approved_by, approved_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version FROM honorary_grants WHERE id = ?
`

func (q *Queries) GetHonoraryGrant(ctx context.Context, id int64) (HonoraryGrant, error) {
	row := q.db.QueryRowContext(ctx, getHonoraryGrant, id)
	var i HonoraryGrant
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsLifetime,
		&i.Reason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, person_id, base_type, lifecycle, joined_on, ended_on, legacy_current_until, legacy_current_until_note, created_at, updated_at, version FROM memberships WHERE id = ?
`

func (q *Queries) GetMembership(ctx context.Context, id int64) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BaseType,
		&i.Lifecycle,
		&i.JoinedOn,
		&i.EndedOn,
		&i.LegacyCurrentUntil,
		&i.LegacyCurrentUntilNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listFCCVerificationsByMembership = `-- name: ListFCCVerificationsByMembership :many
SELECT id, membership_id, call_sign, license_class, verification_source, verified_by, verified_at, expires_at, revoked_at, notes, created_at FROM fcc_verifications WHERE membership_id = ? ORDER BY verified_at DESC
`

func (q *Queries) ListFCCVerificationsByMembership(ctx context.Context, membershipID int64) ([]FccVerification, error) {
	rows, err := q.db.QueryContext(ctx, listFCCVerificationsByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FccVerification{}
	for rows.Next() {
		var i FccVerification
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.CallSign,
			&i.LicenseClass,
			&i.VerificationSource,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHonoraryGrantsByMembership = `-- name: ListHonoraryGrantsByMembership :many
SELECT id, membership_id, starts_on, ends_on, is_lifetime, reason, approved_by, approved_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version FROM honorary_grants WHERE membership_id = ? ORDER BY starts_on DESC
`

func (q *Queries) ListHonoraryGrantsByMembership(ctx context.Context, membershipID int64) ([]HonoraryGrant, error) {
	rows, err := q.db.QueryContext(ctx, listHonoraryGrantsByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HonoraryGrant{}
	for rows.Next() {
		var i HonoraryGrant
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsLifetime,
			&i.Reason,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByPerson = `-- name: ListMembershipsByPerson :many
SELECT id, person_id, base_type, lifecycle, joined_on, ended_on, legacy_current_until, legacy_current_until_note, created_at, updated_at, version FROM memberships WHERE person_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMembershipsByPerson(ctx context.Context, personID int64) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.BaseType,
			&i.Lifecycle,
			&i.JoinedOn,
			&i.EndedOn,
			&i.LegacyCurrentUntil,
			&i.LegacyCurrentUntilNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectMembership = `-- name: RejectMembership :one
UPDATE memberships
SET lifecycle = 'rejected',
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, person_id, base_type, lifecycle, joined_on, ended_on, legacy_current_until, legacy_current_until_note, created_at, updated_at, version
`

type RejectMembershipParams struct {
	ID      int64
	Version int64
}

func (q *Queries) RejectMembership(ctx context.Context, arg RejectMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, rejectMembership, arg.ID, arg.Version)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BaseType,
		&i.Lifecycle,
		&i.JoinedOn,
		&i.EndedOn,
		&i.LegacyCurrentUntil,
		&i.LegacyCurrentUntilNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const revokeFCCVerification = `-- name: RevokeFCCVerification :exec
UPDATE fcc_verifications
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    notes = ?
WHERE id = ?
`

type RevokeFCCVerificationParams struct {
	Notes sql.NullString
	ID    int64
}

func (q *Queries) RevokeFCCVerification(ctx context.Context, arg RevokeFCCVerificationParams) error {
	_, err := q.db.ExecContext(ctx, revokeFCCVerification, arg.Notes, arg.ID)
	return err
}

const revokeHonoraryGrant = `-- name: RevokeHonoraryGrant :exec
UPDATE honorary_grants
SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    revoked_by = ?,
    revoke_reason = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
`

type RevokeHonoraryGrantParams struct {
	RevokedBy    sql.NullInt64
	RevokeReason sql.NullString
	ID           int64
	Version      int64
}

func (q *Queries) RevokeHonoraryGrant(ctx context.Context, arg RevokeHonoraryGrantParams) error {
	_, err := q.db.ExecContext(ctx, revokeHonoraryGrant,
		arg.RevokedBy,
		arg.RevokeReason,
		arg.ID,
		arg.Version,
	)
	return err
}

const transitionLifecycle = `-- name: TransitionLifecycle :one
UPDATE memberships
SET lifecycle = ?, ended_on = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, person_id, base_type, lifecycle, joined_on, ended_on, legacy_current_until, legacy_current_until_note, created_at, updated_at, version
`

type TransitionLifecycleParams struct {
	Lifecycle string
	EndedOn   sql.NullString
	ID        int64
	Version   int64
}

func (q *Queries) TransitionLifecycle(ctx context.Context, arg TransitionLifecycleParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, transitionLifecycle,
		arg.Lifecycle,
		arg.EndedOn,
		arg.ID,
		arg.Version,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.BaseType,
		&i.Lifecycle,
		&i.JoinedOn,
		&i.EndedOn,
		&i.LegacyCurrentUntil,
		&i.LegacyCurrentUntilNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateHonoraryGrant = `-- name: UpdateHonoraryGrant :one
UPDATE honorary_grants
SET reason = ?, ends_on = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, membership_id, starts_on, ends_on, is_lifetime, reason, approved_by, approved_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version
`

type UpdateHonoraryGrantParams struct {
	Reason  string
	EndsOn  sql.NullString
	ID      int64
	Version int64
}

func (q *Queries) UpdateHonoraryGrant(ctx context.Context, arg UpdateHonoraryGrantParams) (HonoraryGrant, error) {
	row := q.db.QueryRowContext(ctx, updateHonoraryGrant,
		arg.Reason,
		arg.EndsOn,
		arg.ID,
		arg.Version,
	)
	var i HonoraryGrant
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsLifetime,
		&i.Reason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
