// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member_access.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countActiveAccessGrant = `-- name: CountActiveAccessGrant :one
SELECT count(*) FROM member_access_grants
 WHERE user_id = ? AND person_id = ? AND revoked_at IS NULL
`

type CountActiveAccessGrantParams struct {
	UserID   int64
	PersonID int64
}

// The single-record authorization probe: does this user hold access to this
// person right now. Returns 0 or 1 because of ux_member_access_active.
func (q *Queries) CountActiveAccessGrant(ctx context.Context, arg CountActiveAccessGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAccessGrant, arg.UserID, arg.PersonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMemberAccessGrant = `-- name: GetMemberAccessGrant :one
SELECT id, user_id, person_id, access_kind, reason, granted_by, granted_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version FROM member_access_grants WHERE id = ?
`

func (q *Queries) GetMemberAccessGrant(ctx context.Context, id int64) (MemberAccessGrant, error) {
	row := q.db.QueryRowContext(ctx, getMemberAccessGrant, id)
	var i MemberAccessGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.AccessKind,
		&i.Reason,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const grantMemberAccess = `-- name: GrantMemberAccess :one

INSERT INTO member_access_grants (
    user_id, person_id, access_kind, reason, granted_by, granted_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, person_id, access_kind, reason, granted_by, granted_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version
`

type GrantMemberAccessParams struct {
	UserID     int64
	PersonID   int64
	AccessKind string
	Reason     sql.NullString
	GrantedBy  sql.NullInt64
	GrantedAt  string
}

// Member record access grants.
//
// This file is the ONLY way authorization learns which person records a user
// may see. Nothing here joins users.person_id, contact_methods.value_norm,
// person_relationships, or role_capabilities: an access decision comes from an
// explicit unrevoked grant or it does not exist.
//
// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
// offset, so a multi-byte character above a query corrupts the SQL it parses.
func (q *Queries) GrantMemberAccess(ctx context.Context, arg GrantMemberAccessParams) (MemberAccessGrant, error) {
	row := q.db.QueryRowContext(ctx, grantMemberAccess,
		arg.UserID,
		arg.PersonID,
		arg.AccessKind,
		arg.Reason,
		arg.GrantedBy,
		arg.GrantedAt,
	)
	var i MemberAccessGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.AccessKind,
		&i.Reason,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listAccessGrantsForPerson = `-- name: ListAccessGrantsForPerson :many
SELECT g.id, g.user_id, g.person_id, g.access_kind, g.reason, g.granted_by, g.granted_at, g.revoked_at, g.revoked_by, g.revoke_reason, g.created_at, g.updated_at, g.version, u.email AS user_email
  FROM member_access_grants g
  JOIN users u ON u.id = g.user_id
 WHERE g.person_id = ?
 ORDER BY g.revoked_at IS NOT NULL, g.granted_at DESC, g.id DESC
`

type ListAccessGrantsForPersonRow struct {
	ID           int64
	UserID       int64
	PersonID     int64
	AccessKind   string
	Reason       sql.NullString
	GrantedBy    sql.NullInt64
	GrantedAt    string
	RevokedAt    sql.NullString
	RevokedBy    sql.NullInt64
	RevokeReason sql.NullString
	CreatedAt    string
	UpdatedAt    string
	Version      int64
	UserEmail    string
}

// Officer view. Includes revoked rows so the history of who could see a record
// is readable, not just the current state.
func (q *Queries) ListAccessGrantsForPerson(ctx context.Context, personID int64) ([]ListAccessGrantsForPersonRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessGrantsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessGrantsForPersonRow{}
	for rows.Next() {
		var i ListAccessGrantsForPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonID,
			&i.AccessKind,
			&i.Reason,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessGrantsForUser = `-- name: ListAccessGrantsForUser :many
SELECT g.id, g.user_id, g.person_id, g.access_kind, g.reason, g.granted_by, g.granted_at, g.revoked_at, g.revoked_by, g.revoke_reason, g.created_at, g.updated_at, g.version, p.display_name AS display_name
  FROM member_access_grants g
  JOIN persons p ON p.id = g.person_id
 WHERE g.user_id = ?
 ORDER BY g.revoked_at IS NOT NULL, p.sort_name, g.id
`

type ListAccessGrantsForUserRow struct {
	ID           int64
	UserID       int64
	PersonID     int64
	AccessKind   string
	Reason       sql.NullString
	GrantedBy    sql.NullInt64
	GrantedAt    string
	RevokedAt    sql.NullString
	RevokedBy    sql.NullInt64
	RevokeReason sql.NullString
	CreatedAt    string
	UpdatedAt    string
	Version      int64
	DisplayName  string
}

// The officer view of one account: every grant it has ever held, revoked ones
// included, so "who could reach this record, and when" stays answerable.
//
// Distinct from ListActiveAccessGrantsForUser, which is the authorization read
// and must return only what currently confers access. Keeping them separate
// means a history view can never accidentally become an authorization answer.
func (q *Queries) ListAccessGrantsForUser(ctx context.Context, userID int64) ([]ListAccessGrantsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessGrantsForUserRow{}
	for rows.Next() {
		var i ListAccessGrantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonID,
			&i.AccessKind,
			&i.Reason,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAccessGrantsForUser = `-- name: ListActiveAccessGrantsForUser :many
SELECT g.id          AS grant_id,
       g.user_id     AS user_id,
       g.person_id   AS person_id,
       g.access_kind AS access_kind,
       g.granted_at  AS granted_at,
       p.display_name AS display_name,
       p.call_sign    AS call_sign
  FROM member_access_grants g
  JOIN persons p ON p.id = g.person_id
 WHERE g.user_id = ?
   AND g.revoked_at IS NULL
 ORDER BY p.sort_name, g.person_id
`

type ListActiveAccessGrantsForUserRow struct {
	GrantID     int64
	UserID      int64
	PersonID    int64
	AccessKind  string
	GrantedAt   string
	DisplayName string
	CallSign    sql.NullString
}

// The authorization read. Loaded per request, so revoking a grant takes effect
// inside a session that is already open.
func (q *Queries) ListActiveAccessGrantsForUser(ctx context.Context, userID int64) ([]ListActiveAccessGrantsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAccessGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAccessGrantsForUserRow{}
	for rows.Next() {
		var i ListActiveAccessGrantsForUserRow
		if err := rows.Scan(
			&i.GrantID,
			&i.UserID,
			&i.PersonID,
			&i.AccessKind,
			&i.GrantedAt,
			&i.DisplayName,
			&i.CallSign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMemberAccess = `-- name: RevokeMemberAccess :one
UPDATE member_access_grants
   SET revoked_at = ?1,
       revoked_by = ?2,
       revoke_reason = ?3,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?4
   AND version = ?5
   AND revoked_at IS NULL
RETURNING id, user_id, person_id, access_kind, reason, granted_by, granted_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at, version
`

type RevokeMemberAccessParams struct {
	RevokedAt    sql.NullString
	RevokedBy    sql.NullInt64
	RevokeReason sql.NullString
	ID           int64
	Version      int64
}

// Version-guarded, so a concurrent revoke cannot silently no-op. A caller that
// gets sql.ErrNoRows maps it to db.ErrStale after confirming the row exists.
func (q *Queries) RevokeMemberAccess(ctx context.Context, arg RevokeMemberAccessParams) (MemberAccessGrant, error) {
	row := q.db.QueryRowContext(ctx, revokeMemberAccess,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevokeReason,
		arg.ID,
		arg.Version,
	)
	var i MemberAccessGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.AccessKind,
		&i.Reason,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
