// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AcsAresSharingEvent struct {
	ID           int64
	PersonID     int64
	Participates int64
	Source       string
	EffectiveAt  string
	ActorUserID  sql.NullInt64
	Reason       sql.NullString
	CreatedAt    string
}

type AppSetting struct {
	Key       string
	Value     string
	UpdatedAt string
}

type AuditEvent struct {
	ID             int64
	OccurredAt     string
	RequestID      sql.NullString
	ActorUserID    sql.NullInt64
	ActorRoleCodes sql.NullString
	Action         string
	ResourceKind   sql.NullString
	ResourceID     sql.NullInt64
	Outcome        string
	ReasonCode     sql.NullString
	DetailJson     sql.NullString
	CreatedAt      string
}

type Capability struct {
	Code        string
	Description string
	Category    string
	CreatedAt   string
}

type ContactMethod struct {
	ID               int64
	PersonID         int64
	Kind             string
	Label            sql.NullString
	ValueRaw         string
	ValueNorm        string
	IsPrimary        int64
	ArchivedAt       sql.NullString
	PostalLine1      sql.NullString
	PostalLine2      sql.NullString
	PostalCity       sql.NullString
	PostalState      sql.NullString
	PostalPostalCode sql.NullString
	PostalCountry    sql.NullString
	CreatedAt        string
	UpdatedAt        string
	Version          int64
}

type ContactMethodVisibilityEvent struct {
	ID              int64
	ContactMethodID int64
	Audience        string
	Source          string
	EffectiveAt     string
	ActorUserID     sql.NullInt64
	Note            sql.NullString
	CreatedAt       string
}

type CoverageEvent struct {
	ID                int64
	MembershipID      int64
	PaidThrough       string
	ReasonKind        string
	Reason            sql.NullString
	PaymentID         sql.NullInt64
	ImportRunID       sql.NullInt64
	SupersedesEventID sql.NullInt64
	SourceNote        sql.NullString
	DecidedBy         sql.NullInt64
	DecidedAt         string
	CreatedAt         string
}

type DuesRate struct {
	Year        int64
	AmountCents int64
	Note        sql.NullString
	SetBy       int64
	SetAt       string
	CreatedAt   string
	UpdatedAt   string
	Version     int64
}

type EmailLink struct {
	ID               int64
	Purpose          string
	UserID           sql.NullInt64
	Email            string
	TokenHash        string
	CreatedAt        string
	ExpiresAt        string
	ConsumedAt       sql.NullString
	RequestedIpHash  sql.NullString
	IntendedRoleCode sql.NullString
}

type ExternalID struct {
	ID         int64
	EntityKind string
	EntityID   int64
	System     string
	ExternalID string
	CreatedAt  string
}

type FccVerification struct {
	ID                 int64
	MembershipID       int64
	CallSign           string
	LicenseClass       sql.NullString
	VerificationSource string
	VerifiedBy         int64
	VerifiedAt         string
	ExpiresAt          sql.NullString
	RevokedAt          sql.NullString
	Notes              sql.NullString
	CreatedAt          string
}

type HonoraryGrant struct {
	ID           int64
	MembershipID int64
	StartsOn     string
	EndsOn       sql.NullString
	IsLifetime   int64
	Reason       string
	ApprovedBy   int64
	ApprovedAt   string
	RevokedAt    sql.NullString
	RevokedBy    sql.NullInt64
	RevokeReason sql.NullString
	CreatedAt    string
	UpdatedAt    string
	Version      int64
}

type IdempotencyRecord struct {
	ID             int64
	ActorUserID    int64
	Operation      string
	IdempotencyKey string
	RequestHash    string
	ResourceKind   sql.NullString
	ResourceID     sql.NullInt64
	CreatedAt      string
}

type ImportRun struct {
	ID                int64
	SourceKind        string
	SourceFilename    string
	SourceSha256      string
	UploadedBy        int64
	UploadedAt        string
	Status            string
	IdempotencyKey    string
	CommittedBy       sql.NullInt64
	CommittedAt       sql.NullString
	ResultSummaryJson sql.NullString
	CreatedAt         string
	UpdatedAt         string
	Version           int64
}

type Membership struct {
	ID        int64
	PersonID  int64
	BaseType  string
	Lifecycle string
	JoinedOn  sql.NullString
	EndedOn   sql.NullString
	CreatedAt string
	UpdatedAt string
	Version   int64
}

type MembershipApproval struct {
	ID           int64
	MembershipID int64
	Decision     string
	ApprovedType sql.NullString
	DecidedBy    int64
	DecidedAt    string
	Reason       sql.NullString
	CreatedAt    string
}

type Note struct {
	ID          int64
	SubjectKind string
	SubjectID   int64
	Category    string
	Visibility  string
	Body        string
	AuthorID    int64
	Source      string
	CreatedAt   string
	UpdatedAt   string
	Version     int64
}

type NoteRevision struct {
	ID       int64
	NoteID   int64
	Body     string
	EditedBy int64
	EditedAt string
	Reason   sql.NullString
}

type Payment struct {
	ID                int64
	MembershipID      int64
	BatchID           sql.NullInt64
	AmountCents       int64
	Method            string
	Reference         sql.NullString
	ReceivedOn        string
	ReceivedByOfficer sql.NullString
	EnteredBy         int64
	EnteredAt         string
	ReceiptCode       string
	EntryKind         string
	CorrectsPaymentID sql.NullInt64
	TreasurerNote     sql.NullString
	CreatedAt         string
}

type PaymentBatch struct {
	ID                 int64
	Label              string
	State              string
	DefaultAmountCents sql.NullInt64
	DefaultPaidThrough sql.NullString
	OpenedBy           int64
	OpenedAt           string
	PostedBy           sql.NullInt64
	PostedAt           sql.NullString
	AbandonedBy        sql.NullInt64
	AbandonedAt        sql.NullString
	AbandonReason      sql.NullString
	CreatedAt          string
	UpdatedAt          string
	Version            int64
}

type PaymentBatchEntry struct {
	ID                int64
	BatchID           int64
	MembershipID      int64
	Sequence          int64
	AmountCents       int64
	Method            string
	Reference         sql.NullString
	ReceivedOn        string
	ReceivedByOfficer sql.NullString
	PaidThrough       string
	TreasurerNote     sql.NullString
	CreatedAt         string
	UpdatedAt         string
	Version           int64
}

type PaymentCorrection struct {
	ID                   int64
	OriginalPaymentID    int64
	ReversalPaymentID    int64
	ReplacementPaymentID int64
	Reason               string
	CorrectedBy          int64
	CorrectedAt          string
	CreatedAt            string
}

type Person struct {
	ID            int64
	DisplayName   string
	SortName      string
	CallSign      sql.NullString
	DeceasedAt    sql.NullString
	DeactivatedAt sql.NullString
	CreatedAt     string
	UpdatedAt     string
	Version       int64
}

type ReconciliationDecision struct {
	ID                int64
	StagedImportRowID int64
	DecidedBy         int64
	DecidedAt         string
	Action            string
	PayloadJson       sql.NullString
	CreatedAt         string
}

type Role struct {
	Code        string
	Description string
	Kind        string
	CreatedAt   string
}

type RoleCapability struct {
	RoleCode       string
	CapabilityCode string
}

type Session struct {
	ID         string
	UserID     int64
	CreatedAt  string
	LastSeenAt string
	ExpiresAt  string
	IpHash     sql.NullString
	UserAgent  sql.NullString
	RevokedAt  sql.NullString
}

type StagedImportRow struct {
	ID                   int64
	ImportRunID          int64
	SourceRowIndex       int64
	SourceExternalID     sql.NullString
	RawJson              string
	NormalizedJson       string
	MatchPersonID        sql.NullInt64
	MatchMethod          sql.NullString
	ProposedAction       string
	ProposedChangesJson  sql.NullString
	ValidationErrorsJson sql.NullString
	RequiresManual       int64
	ManualReason         sql.NullString
	CreatedAt            string
}

type User struct {
	ID                 int64
	Email              string
	EmailVerifiedAt    sql.NullString
	PasswordHash       sql.NullString
	PasswordAlgoParams sql.NullString
	PersonID           sql.NullInt64
	IsActive           int64
	LastLoginAt        sql.NullString
	FailedLoginCount   int64
	LockedUntil        sql.NullString
	CreatedAt          string
	UpdatedAt          string
	Version            int64
}

type UserCapabilityGrant struct {
	ID             int64
	UserID         int64
	CapabilityCode string
	GrantedBy      int64
	GrantedAt      string
	RevokedAt      sql.NullString
	RevokedBy      sql.NullInt64
	Reason         sql.NullString
	CreatedAt      string
}

type UserRoleGrant struct {
	ID        int64
	UserID    int64
	RoleCode  string
	GrantedBy int64
	GrantedAt string
	RevokedAt sql.NullString
	RevokedBy sql.NullInt64
	Reason    sql.NullString
	CreatedAt string
}
