// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (subject_kind, subject_id, category, visibility, body, author_id, source)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, subject_kind, subject_id, category, visibility, body, author_id, source, created_at, updated_at, version
`

type CreateNoteParams struct {
	SubjectKind string
	SubjectID   int64
	Category    string
	Visibility  string
	Body        string
	AuthorID    int64
	Source      string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Category,
		arg.Visibility,
		arg.Body,
		arg.AuthorID,
		arg.Source,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Category,
		&i.Visibility,
		&i.Body,
		&i.AuthorID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createNoteRevision = `-- name: CreateNoteRevision :one
INSERT INTO note_revisions (note_id, body, edited_by, edited_at, reason)
VALUES (?, ?, ?, ?, ?)
RETURNING id, note_id, body, edited_by, edited_at, reason
`

type CreateNoteRevisionParams struct {
	NoteID   int64
	Body     string
	EditedBy int64
	EditedAt string
	Reason   sql.NullString
}

func (q *Queries) CreateNoteRevision(ctx context.Context, arg CreateNoteRevisionParams) (NoteRevision, error) {
	row := q.db.QueryRowContext(ctx, createNoteRevision,
		arg.NoteID,
		arg.Body,
		arg.EditedBy,
		arg.EditedAt,
		arg.Reason,
	)
	var i NoteRevision
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.Body,
		&i.EditedBy,
		&i.EditedAt,
		&i.Reason,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT id, subject_kind, subject_id, category, visibility, body, author_id, source, created_at, updated_at, version FROM notes WHERE id = ?
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Category,
		&i.Visibility,
		&i.Body,
		&i.AuthorID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, subject_kind, subject_id, category, visibility, body, author_id, source, created_at, updated_at, version FROM notes
WHERE subject_kind = ? AND subject_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotesParams struct {
	SubjectKind string
	SubjectID   int64
	Limit       int64
	Offset      int64
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Category,
			&i.Visibility,
			&i.Body,
			&i.AuthorID,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET body = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, subject_kind, subject_id, category, visibility, body, author_id, source, created_at, updated_at, version
`

type UpdateNoteParams struct {
	Body    string
	ID      int64
	Version int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Body, arg.ID, arg.Version)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Category,
		&i.Visibility,
		&i.Body,
		&i.AuthorID,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
