// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (display_name, sort_name, call_sign, license_class, volunteer_examiner)
VALUES (?, ?, ?, ?, ?)
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner
`

type CreatePersonParams struct {
	DisplayName       string
	SortName          string
	CallSign          sql.NullString
	LicenseClass      sql.NullString
	VolunteerExaminer int64
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson,
		arg.DisplayName,
		arg.SortName,
		arg.CallSign,
		arg.LicenseClass,
		arg.VolunteerExaminer,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}

const deactivatePerson = `-- name: DeactivatePerson :one
UPDATE persons
SET deactivated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner
`

type DeactivatePersonParams struct {
	ID      int64
	Version int64
}

func (q *Queries) DeactivatePerson(ctx context.Context, arg DeactivatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, deactivatePerson, arg.ID, arg.Version)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner FROM persons WHERE id = ?
`

func (q *Queries) GetPerson(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}

const getPersonByCallSign = `-- name: GetPersonByCallSign :one
SELECT id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner FROM persons WHERE call_sign = ?
`

func (q *Queries) GetPersonByCallSign(ctx context.Context, callSign sql.NullString) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByCallSign, callSign)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}

const listPersons = `-- name: ListPersons :many
SELECT p.id, p.display_name, p.sort_name, p.call_sign, p.deceased_at, p.deactivated_at,
       p.version, p.created_at, p.updated_at,
       CAST(COALESCE((SELECT m.base_type FROM memberships m
                       WHERE m.person_id = p.id AND m.ended_on IS NULL
                       ORDER BY m.created_at DESC, m.id DESC LIMIT 1), '') AS TEXT) AS base_type
FROM persons p
WHERE p.deactivated_at IS NULL
ORDER BY p.sort_name
LIMIT ? OFFSET ?
`

type ListPersonsParams struct {
	Limit  int64
	Offset int64
}

type ListPersonsRow struct {
	ID            int64
	DisplayName   string
	SortName      string
	CallSign      sql.NullString
	DeceasedAt    sql.NullString
	DeactivatedAt sql.NullString
	Version       int64
	CreatedAt     string
	UpdatedAt     string
	BaseType      string
}

// base_type comes from the person's current membership, so the list can say
// what each person is. It was absent, and the members list rendered a dash in
// the Type column for everyone while the record page showed the type
// (bcars-portal-ges).
//
// The subquery takes the most recent membership that has not ended, which is
// the one the record page shows. A person with no membership yields NULL, and
// the list still says "-" for them -- correctly, this time.
func (q *Queries) ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsRow{}
	for rows.Next() {
		var i ListPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.SortName,
			&i.CallSign,
			&i.DeceasedAt,
			&i.DeactivatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByName = `-- name: ListPersonsByName :many
SELECT p.id, p.display_name, p.sort_name, p.call_sign, p.deceased_at, p.deactivated_at,
       p.version, p.created_at, p.updated_at,
       CAST(COALESCE((SELECT m.base_type FROM memberships m
                       WHERE m.person_id = p.id AND m.ended_on IS NULL
                       ORDER BY m.created_at DESC, m.id DESC LIMIT 1), '') AS TEXT) AS base_type
FROM persons p
WHERE (p.display_name LIKE '%' || ? || '%' OR p.sort_name LIKE '%' || ? || '%')
  AND p.deactivated_at IS NULL
ORDER BY p.sort_name
LIMIT ? OFFSET ?
`

type ListPersonsByNameParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
	Limit   int64
	Offset  int64
}

type ListPersonsByNameRow struct {
	ID            int64
	DisplayName   string
	SortName      string
	CallSign      sql.NullString
	DeceasedAt    sql.NullString
	DeactivatedAt sql.NullString
	Version       int64
	CreatedAt     string
	UpdatedAt     string
	BaseType      string
}

// The same columns as ListPersons, including the current membership's
// base_type; see the note there.
func (q *Queries) ListPersonsByName(ctx context.Context, arg ListPersonsByNameParams) ([]ListPersonsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonsByName,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsByNameRow{}
	for rows.Next() {
		var i ListPersonsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.SortName,
			&i.CallSign,
			&i.DeceasedAt,
			&i.DeactivatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeceased = `-- name: MarkDeceased :one
UPDATE persons
SET deceased_at = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner
`

type MarkDeceasedParams struct {
	DeceasedAt sql.NullString
	ID         int64
	Version    int64
}

func (q *Queries) MarkDeceased(ctx context.Context, arg MarkDeceasedParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, markDeceased, arg.DeceasedAt, arg.ID, arg.Version)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}

const reactivatePerson = `-- name: ReactivatePerson :one
UPDATE persons
SET deactivated_at = NULL,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner
`

type ReactivatePersonParams struct {
	ID      int64
	Version int64
}

func (q *Queries) ReactivatePerson(ctx context.Context, arg ReactivatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, reactivatePerson, arg.ID, arg.Version)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET display_name = ?, sort_name = ?, call_sign = ?,
    license_class = ?, volunteer_examiner = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version, license_class, volunteer_examiner
`

type UpdatePersonParams struct {
	DisplayName       string
	SortName          string
	CallSign          sql.NullString
	LicenseClass      sql.NullString
	VolunteerExaminer int64
	ID                int64
	Version           int64
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePerson,
		arg.DisplayName,
		arg.SortName,
		arg.CallSign,
		arg.LicenseClass,
		arg.VolunteerExaminer,
		arg.ID,
		arg.Version,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.LicenseClass,
		&i.VolunteerExaminer,
	)
	return i, err
}
