// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (display_name, sort_name, call_sign)
VALUES (?, ?, ?)
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version
`

type CreatePersonParams struct {
	DisplayName string
	SortName    string
	CallSign    sql.NullString
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.DisplayName, arg.SortName, arg.CallSign)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const deactivatePerson = `-- name: DeactivatePerson :one
UPDATE persons
SET deactivated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version
`

type DeactivatePersonParams struct {
	ID      int64
	Version int64
}

func (q *Queries) DeactivatePerson(ctx context.Context, arg DeactivatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, deactivatePerson, arg.ID, arg.Version)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version FROM persons WHERE id = ?
`

func (q *Queries) GetPerson(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPersonByCallSign = `-- name: GetPersonByCallSign :one
SELECT id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version FROM persons WHERE call_sign = ?
`

func (q *Queries) GetPersonByCallSign(ctx context.Context, callSign sql.NullString) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByCallSign, callSign)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listPersons = `-- name: ListPersons :many
SELECT id, display_name, sort_name, call_sign, deceased_at, deactivated_at, version, created_at, updated_at
FROM persons
WHERE deactivated_at IS NULL
ORDER BY sort_name
LIMIT ? OFFSET ?
`

type ListPersonsParams struct {
	Limit  int64
	Offset int64
}

type ListPersonsRow struct {
	ID            int64
	DisplayName   string
	SortName      string
	CallSign      sql.NullString
	DeceasedAt    sql.NullString
	DeactivatedAt sql.NullString
	Version       int64
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsRow{}
	for rows.Next() {
		var i ListPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.SortName,
			&i.CallSign,
			&i.DeceasedAt,
			&i.DeactivatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByName = `-- name: ListPersonsByName :many
SELECT id, display_name, sort_name, call_sign, deceased_at, deactivated_at, version, created_at, updated_at
FROM persons
WHERE (display_name LIKE '%' || ? || '%' OR sort_name LIKE '%' || ? || '%')
  AND deactivated_at IS NULL
ORDER BY sort_name
LIMIT ? OFFSET ?
`

type ListPersonsByNameParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
	Limit   int64
	Offset  int64
}

type ListPersonsByNameRow struct {
	ID            int64
	DisplayName   string
	SortName      string
	CallSign      sql.NullString
	DeceasedAt    sql.NullString
	DeactivatedAt sql.NullString
	Version       int64
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) ListPersonsByName(ctx context.Context, arg ListPersonsByNameParams) ([]ListPersonsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonsByName,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsByNameRow{}
	for rows.Next() {
		var i ListPersonsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.SortName,
			&i.CallSign,
			&i.DeceasedAt,
			&i.DeactivatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeceased = `-- name: MarkDeceased :one
UPDATE persons
SET deceased_at = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version
`

type MarkDeceasedParams struct {
	DeceasedAt sql.NullString
	ID         int64
	Version    int64
}

func (q *Queries) MarkDeceased(ctx context.Context, arg MarkDeceasedParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, markDeceased, arg.DeceasedAt, arg.ID, arg.Version)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const reactivatePerson = `-- name: ReactivatePerson :one
UPDATE persons
SET deactivated_at = NULL,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version
`

type ReactivatePersonParams struct {
	ID      int64
	Version int64
}

func (q *Queries) ReactivatePerson(ctx context.Context, arg ReactivatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, reactivatePerson, arg.ID, arg.Version)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET display_name = ?, sort_name = ?, call_sign = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
RETURNING id, display_name, sort_name, call_sign, deceased_at, deactivated_at, created_at, updated_at, version
`

type UpdatePersonParams struct {
	DisplayName string
	SortName    string
	CallSign    sql.NullString
	ID          int64
	Version     int64
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePerson,
		arg.DisplayName,
		arg.SortName,
		arg.CallSign,
		arg.ID,
		arg.Version,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SortName,
		&i.CallSign,
		&i.DeceasedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
