// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAcsAresSharingEvent = `-- name: CreateAcsAresSharingEvent :one
INSERT INTO acs_ares_sharing_events (person_id, participates, source, effective_at, actor_user_id, reason)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, person_id, participates, source, effective_at, actor_user_id, reason, created_at
`

type CreateAcsAresSharingEventParams struct {
	PersonID     int64
	Participates int64
	Source       string
	EffectiveAt  string
	ActorUserID  sql.NullInt64
	Reason       sql.NullString
}

func (q *Queries) CreateAcsAresSharingEvent(ctx context.Context, arg CreateAcsAresSharingEventParams) (AcsAresSharingEvent, error) {
	row := q.db.QueryRowContext(ctx, createAcsAresSharingEvent,
		arg.PersonID,
		arg.Participates,
		arg.Source,
		arg.EffectiveAt,
		arg.ActorUserID,
		arg.Reason,
	)
	var i AcsAresSharingEvent
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Participates,
		&i.Source,
		&i.EffectiveAt,
		&i.ActorUserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createVisibilityEvent = `-- name: CreateVisibilityEvent :one
INSERT INTO contact_method_visibility_events (contact_method_id, audience, source, effective_at, actor_user_id, note)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, contact_method_id, audience, source, effective_at, actor_user_id, note, created_at
`

type CreateVisibilityEventParams struct {
	ContactMethodID int64
	Audience        string
	Source          string
	EffectiveAt     string
	ActorUserID     sql.NullInt64
	Note            sql.NullString
}

func (q *Queries) CreateVisibilityEvent(ctx context.Context, arg CreateVisibilityEventParams) (ContactMethodVisibilityEvent, error) {
	row := q.db.QueryRowContext(ctx, createVisibilityEvent,
		arg.ContactMethodID,
		arg.Audience,
		arg.Source,
		arg.EffectiveAt,
		arg.ActorUserID,
		arg.Note,
	)
	var i ContactMethodVisibilityEvent
	err := row.Scan(
		&i.ID,
		&i.ContactMethodID,
		&i.Audience,
		&i.Source,
		&i.EffectiveAt,
		&i.ActorUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAcsAresSharing = `-- name: GetLatestAcsAresSharing :one
SELECT id, person_id, participates, source, effective_at, actor_user_id, reason, created_at FROM acs_ares_sharing_events
WHERE person_id = ?
ORDER BY effective_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAcsAresSharing(ctx context.Context, personID int64) (AcsAresSharingEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestAcsAresSharing, personID)
	var i AcsAresSharingEvent
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Participates,
		&i.Source,
		&i.EffectiveAt,
		&i.ActorUserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVisibility = `-- name: GetLatestVisibility :one
SELECT id, contact_method_id, audience, source, effective_at, actor_user_id, note, created_at FROM contact_method_visibility_events
WHERE contact_method_id = ?
ORDER BY effective_at DESC
LIMIT 1
`

func (q *Queries) GetLatestVisibility(ctx context.Context, contactMethodID int64) (ContactMethodVisibilityEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestVisibility, contactMethodID)
	var i ContactMethodVisibilityEvent
	err := row.Scan(
		&i.ID,
		&i.ContactMethodID,
		&i.Audience,
		&i.Source,
		&i.EffectiveAt,
		&i.ActorUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listAcsAresSharingHistory = `-- name: ListAcsAresSharingHistory :many
SELECT id, person_id, participates, source, effective_at, actor_user_id, reason, created_at FROM acs_ares_sharing_events
WHERE person_id = ?
ORDER BY effective_at DESC
`

func (q *Queries) ListAcsAresSharingHistory(ctx context.Context, personID int64) ([]AcsAresSharingEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAcsAresSharingHistory, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcsAresSharingEvent{}
	for rows.Next() {
		var i AcsAresSharingEvent
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Participates,
			&i.Source,
			&i.EffectiveAt,
			&i.ActorUserID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibilityHistory = `-- name: ListVisibilityHistory :many
SELECT id, contact_method_id, audience, source, effective_at, actor_user_id, note, created_at FROM contact_method_visibility_events
WHERE contact_method_id = ?
ORDER BY effective_at DESC
`

func (q *Queries) ListVisibilityHistory(ctx context.Context, contactMethodID int64) ([]ContactMethodVisibilityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listVisibilityHistory, contactMethodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactMethodVisibilityEvent{}
	for rows.Next() {
		var i ContactMethodVisibilityEvent
		if err := rows.Scan(
			&i.ID,
			&i.ContactMethodID,
			&i.Audience,
			&i.Source,
			&i.EffectiveAt,
			&i.ActorUserID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
