// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActiveRolesForUser(ctx context.Context, userID int64) ([]ActiveRolesForUserRow, error)
	ApproveMembership(ctx context.Context, arg ApproveMembershipParams) (Membership, error)
	ArchiveContactMethod(ctx context.Context, arg ArchiveContactMethodParams) (ContactMethod, error)
	// ClearPrimaryForPerson and SetPrimary are DELIBERATELY unconditional: they
	// are the two halves of "make this contact method the primary one", a
	// set-valued operation with no single row whose version the caller could hold.
	// Adding a version parameter would check one row while the sweep across the
	// others stayed unchecked, which is worse than checking nothing.
	//
	// They still bump version, and that is correct: a caller holding a stale token
	// for an affected row must fail on their NEXT targeted update rather than
	// overwrite a change they never saw.
	//
	// Every OTHER mutation in this file that takes a version parameter must be
	// :one with RETURNING so a conflict is detectable; see scripts/check-version-conflicts.sh.
	ClearPrimaryForPerson(ctx context.Context, personID int64) error
	CommitImportRun(ctx context.Context, arg CommitImportRunParams) (ImportRun, error)
	ConsumeEmailLink(ctx context.Context, id int64) error
	CountStagedRowsByAction(ctx context.Context, importRunID int64) ([]CountStagedRowsByActionRow, error)
	CountUnresolvedManualRows(ctx context.Context, importRunID int64) (int64, error)
	CreateAcsAresSharingEvent(ctx context.Context, arg CreateAcsAresSharingEventParams) (AcsAresSharingEvent, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateCapabilityGrant(ctx context.Context, arg CreateCapabilityGrantParams) (UserCapabilityGrant, error)
	CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (ContactMethod, error)
	CreateEmailLink(ctx context.Context, arg CreateEmailLinkParams) (EmailLink, error)
	CreateExternalID(ctx context.Context, arg CreateExternalIDParams) (ExternalID, error)
	CreateFCCVerification(ctx context.Context, arg CreateFCCVerificationParams) (FccVerification, error)
	CreateHonoraryGrant(ctx context.Context, arg CreateHonoraryGrantParams) (HonoraryGrant, error)
	CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateMembershipApproval(ctx context.Context, arg CreateMembershipApprovalParams) (MembershipApproval, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteRevision(ctx context.Context, arg CreateNoteRevisionParams) (NoteRevision, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreateReconciliationDecision(ctx context.Context, arg CreateReconciliationDecisionParams) (ReconciliationDecision, error)
	CreateRoleGrant(ctx context.Context, arg CreateRoleGrantParams) (UserRoleGrant, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStagedRow(ctx context.Context, arg CreateStagedRowParams) (StagedImportRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVisibilityEvent(ctx context.Context, arg CreateVisibilityEventParams) (ContactMethodVisibilityEvent, error)
	DeactivatePerson(ctx context.Context, arg DeactivatePersonParams) (Person, error)
	DeleteExpiredSessions(ctx context.Context) error
	EffectiveCapabilities(ctx context.Context, arg EffectiveCapabilitiesParams) ([]string, error)
	ExpireHonoraryGrant(ctx context.Context, arg ExpireHonoraryGrantParams) (HonoraryGrant, error)
	FindContactMethodByNorm(ctx context.Context, arg FindContactMethodByNormParams) ([]ContactMethod, error)
	FindExternalID(ctx context.Context, arg FindExternalIDParams) (ExternalID, error)
	GetContactMethod(ctx context.Context, id int64) (ContactMethod, error)
	GetEmailLinkByTokenHash(ctx context.Context, tokenHash string) (EmailLink, error)
	GetFCCVerification(ctx context.Context, id int64) (FccVerification, error)
	GetHonoraryGrant(ctx context.Context, id int64) (HonoraryGrant, error)
	GetImportRun(ctx context.Context, id int64) (ImportRun, error)
	GetImportRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ImportRun, error)
	GetLatestAcsAresSharing(ctx context.Context, personID int64) (AcsAresSharingEvent, error)
	GetLatestVisibility(ctx context.Context, contactMethodID int64) (ContactMethodVisibilityEvent, error)
	GetMembership(ctx context.Context, id int64) (Membership, error)
	GetNote(ctx context.Context, id int64) (Note, error)
	GetPerson(ctx context.Context, id int64) (Person, error)
	GetPersonByCallSign(ctx context.Context, callSign sql.NullString) (Person, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetStagedRow(ctx context.Context, id int64) (StagedImportRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	IncrementFailedLogin(ctx context.Context, id int64) error
	ListAcsAresSharingHistory(ctx context.Context, personID int64) ([]AcsAresSharingEvent, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error)
	ListCapabilities(ctx context.Context) ([]Capability, error)
	ListContactMethods(ctx context.Context, personID int64) ([]ContactMethod, error)
	ListDecisionsForRow(ctx context.Context, stagedImportRowID int64) ([]ReconciliationDecision, error)
	ListExternalIDsForEntity(ctx context.Context, arg ListExternalIDsForEntityParams) ([]ExternalID, error)
	ListFCCVerificationsByMembership(ctx context.Context, membershipID int64) ([]FccVerification, error)
	ListHonoraryGrantsByMembership(ctx context.Context, membershipID int64) ([]HonoraryGrant, error)
	ListImportRuns(ctx context.Context, arg ListImportRunsParams) ([]ImportRun, error)
	ListMembershipsByPerson(ctx context.Context, personID int64) ([]Membership, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
	ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error)
	ListPersonsByName(ctx context.Context, arg ListPersonsByNameParams) ([]ListPersonsByNameRow, error)
	ListRoleCapabilities(ctx context.Context) ([]RoleCapability, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListStagedRows(ctx context.Context, arg ListStagedRowsParams) ([]StagedImportRow, error)
	ListStagedRowsRequiringManual(ctx context.Context, arg ListStagedRowsRequiringManualParams) ([]StagedImportRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVisibilityHistory(ctx context.Context, contactMethodID int64) ([]ContactMethodVisibilityEvent, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	MarkDeceased(ctx context.Context, arg MarkDeceasedParams) (Person, error)
	ReactivatePerson(ctx context.Context, arg ReactivatePersonParams) (Person, error)
	RejectMembership(ctx context.Context, arg RejectMembershipParams) (Membership, error)
	RevokeAllSessionsForUser(ctx context.Context, userID int64) error
	RevokeCapabilityGrant(ctx context.Context, arg RevokeCapabilityGrantParams) error
	RevokeFCCVerification(ctx context.Context, arg RevokeFCCVerificationParams) error
	RevokeHonoraryGrant(ctx context.Context, arg RevokeHonoraryGrantParams) (HonoraryGrant, error)
	RevokeRoleGrant(ctx context.Context, arg RevokeRoleGrantParams) error
	RevokeSession(ctx context.Context, id string) error
	RoleExists(ctx context.Context, code string) (bool, error)
	// SearchAuditEvents is the general filtered listing behind GET /audit-events.
	// Every filter is optional (pass NULL to skip it) and all filters compose.
	// action is matched as a prefix (instr(...) = 1 rather than LIKE, so the
	// caller's value needs no wildcard escaping); the rest are exact matches.
	// The tiebreak on id keeps the order total, which offset paging requires.
	SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]AuditEvent, error)
	SetPrimary(ctx context.Context, id int64) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TransitionLifecycle(ctx context.Context, arg TransitionLifecycleParams) (Membership, error)
	UpdateContactMethod(ctx context.Context, arg UpdateContactMethodParams) (ContactMethod, error)
	// is_lifetime is written explicitly because the table CHECK forbids a lifetime
	// grant from carrying an end date; giving a grant an end date converts it to a
	// term grant.
	UpdateHonoraryGrant(ctx context.Context, arg UpdateHonoraryGrantParams) (HonoraryGrant, error)
	UpdateImportRunStatus(ctx context.Context, arg UpdateImportRunStatusParams) (ImportRun, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdateStagedRowAction(ctx context.Context, arg UpdateStagedRowActionParams) (StagedImportRow, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
