// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActiveRolesForUser(ctx context.Context, userID int64) ([]ActiveRolesForUserRow, error)
	ApproveMembership(ctx context.Context, arg ApproveMembershipParams) (Membership, error)
	ArchiveContactMethod(ctx context.Context, arg ArchiveContactMethodParams) (ContactMethod, error)
	ArchivePersonRelationship(ctx context.Context, arg ArchivePersonRelationshipParams) (PersonRelationship, error)
	// ClearPrimaryForPerson and SetPrimary are DELIBERATELY unconditional: they
	// are the two halves of "make this contact method the primary one", a
	// set-valued operation with no single row whose version the caller could hold.
	// Adding a version parameter would check one row while the sweep across the
	// others stayed unchecked, which is worse than checking nothing.
	//
	// They still bump version, and that is correct: a caller holding a stale token
	// for an affected row must fail on their NEXT targeted update rather than
	// overwrite a change they never saw.
	//
	// Every OTHER mutation in this file that takes a version parameter must be
	// :one with RETURNING so a conflict is detectable; see scripts/check-version-conflicts.sh.
	ClearPrimaryForPerson(ctx context.Context, personID int64) error
	CommitImportRun(ctx context.Context, arg CommitImportRunParams) (ImportRun, error)
	// Records which resource a claimed key produced, so a retry can return the
	// original result instead of doing the work twice.
	CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) error
	ConsumeEmailLink(ctx context.Context, id int64) error
	//
	// The single-record authorization probe: does this user hold access to this
	// person right now. Returns 0 or 1 because of ux_member_access_active.
	CountActiveAccessGrant(ctx context.Context, arg CountActiveAccessGrantParams) (int64, error)
	// The member directory (bcars-portal-4ux.7, extended by 4ux.14).
	//
	// Contact values are filtered HERE, in SQL, not in a service or a template. A
	// value the caller may not see is never selected, so it cannot be leaked by a
	// DTO field someone forgets to strip, a template that renders the wrong
	// variable, or a debug log.
	//
	// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character above a query corrupts the SQL it parses.
	//
	// The caller's eligibility probe: does this user hold an active grant to a
	// person whose membership is an active approved FULL membership.
	//
	// Associates may hold grants and use their own profile, but may not browse the
	// directory. Eligibility is deliberately a separate question from holding the
	// directory.read capability, which is why the capability alone never answers
	// it.
	CountDirectoryEligibleGrants(ctx context.Context, userID int64) (int64, error)
	//
	// The same population as ListDirectoryEntries, for pagination. It shares the
	// membership filter so a total always matches what is being listed, and does
	// NOT share the contact filtering, because a total must not depend on what the
	// caller may see.
	CountDirectoryEntries(ctx context.Context, arg CountDirectoryEntriesParams) (int64, error)
	//
	// A request resolves only when this reaches zero.
	CountPendingChangeRequestItems(ctx context.Context, requestID int64) (int64, error)
	//
	// Attempts from one source within the window, whatever their outcome. Counting
	// limited attempts too means sustained hammering keeps extending the block
	// rather than draining it, which is the intended behaviour for abuse.
	CountRequestAttemptsBySource(ctx context.Context, arg CountRequestAttemptsBySourceParams) (int64, error)
	CountRequestAttemptsByTarget(ctx context.Context, arg CountRequestAttemptsByTargetParams) (int64, error)
	CountStagedRowsByAction(ctx context.Context, importRunID int64) ([]CountStagedRowsByActionRow, error)
	CountUnresolvedManualRows(ctx context.Context, importRunID int64) (int64, error)
	CreateAcsAresSharingEvent(ctx context.Context, arg CreateAcsAresSharingEventParams) (AcsAresSharingEvent, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateCapabilityGrant(ctx context.Context, arg CreateCapabilityGrantParams) (UserCapabilityGrant, error)
	// Member change requests and their typed items.
	//
	// No query in this file writes persons, contact_methods, memberships, or
	// preference events. A request records what someone PROPOSED; only the review
	// and apply path (bcars-portal-4ux.3) calls the domain services that change
	// canonical data, and only for an approved item.
	//
	// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character above a query corrupts the SQL it parses.
	CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (MemberChangeRequest, error)
	CreateChangeRequestItem(ctx context.Context, arg CreateChangeRequestItemParams) (MemberChangeRequestItem, error)
	CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (ContactMethod, error)
	CreateCoverageEvent(ctx context.Context, arg CreateCoverageEventParams) (CoverageEvent, error)
	CreateEmailLink(ctx context.Context, arg CreateEmailLinkParams) (EmailLink, error)
	CreateExternalID(ctx context.Context, arg CreateExternalIDParams) (ExternalID, error)
	CreateFCCVerification(ctx context.Context, arg CreateFCCVerificationParams) (FccVerification, error)
	CreateHonoraryGrant(ctx context.Context, arg CreateHonoraryGrantParams) (HonoraryGrant, error)
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyRecord, error)
	CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateMembershipApproval(ctx context.Context, arg CreateMembershipApprovalParams) (MembershipApproval, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteRevision(ctx context.Context, arg CreateNoteRevisionParams) (NoteRevision, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Rate writes live in dues.sql: InsertDuesRate and the version-guarded
	// UpdateDuesRate. There is deliberately no blind upsert, so a revision cannot
	// overwrite another officer's without presenting the version it saw.
	CreatePaymentBatch(ctx context.Context, arg CreatePaymentBatchParams) (PaymentBatch, error)
	CreatePaymentBatchEntry(ctx context.Context, arg CreatePaymentBatchEntryParams) (PaymentBatchEntry, error)
	CreatePaymentCorrection(ctx context.Context, arg CreatePaymentCorrectionParams) (PaymentCorrection, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	// Informational person relationships.
	//
	// These queries are read and write only against person_relationships. None of
	// them touches member_access_grants, sessions, users, or role_capabilities,
	// because a relationship confers no authority. Adding a spouse does not let
	// either person see the other's record; an officer grants that separately.
	//
	// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character above a query corrupts the SQL it parses.
	CreatePersonRelationship(ctx context.Context, arg CreatePersonRelationshipParams) (PersonRelationship, error)
	CreateReconciliationDecision(ctx context.Context, arg CreateReconciliationDecisionParams) (ReconciliationDecision, error)
	CreateRoleGrant(ctx context.Context, arg CreateRoleGrantParams) (UserRoleGrant, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStagedRow(ctx context.Context, arg CreateStagedRowParams) (StagedImportRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVisibilityEvent(ctx context.Context, arg CreateVisibilityEventParams) (ContactMethodVisibilityEvent, error)
	CreateWorksheetRow(ctx context.Context, arg CreateWorksheetRowParams) (DuesWorksheetRow, error)
	// Renewal worksheet runs and their snapshot rows.
	//
	// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character above a query corrupts the SQL it parses.
	CreateWorksheetRun(ctx context.Context, arg CreateWorksheetRunParams) (DuesWorksheetRun, error)
	DeactivatePerson(ctx context.Context, arg DeactivatePersonParams) (Person, error)
	//
	// Records a decision without applying anything. Guarded on the item version
	// AND on still being pending, so a second reviewer deciding the same item gets
	// no rows rather than overwriting the first decision.
	DecideChangeRequestItem(ctx context.Context, arg DecideChangeRequestItemParams) (MemberChangeRequestItem, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeletePaymentBatchEntry(ctx context.Context, arg DeletePaymentBatchEntryParams) (sql.Result, error)
	//
	// Pruning. The table is an abuse control, not a retention record; rows older
	// than the longest window answer no question.
	DeleteRequestAttemptsBefore(ctx context.Context, attemptedAt string) error
	EffectiveCapabilities(ctx context.Context, arg EffectiveCapabilitiesParams) ([]string, error)
	ExpireHonoraryGrant(ctx context.Context, arg ExpireHonoraryGrantParams) (HonoraryGrant, error)
	FindContactMethodByNorm(ctx context.Context, arg FindContactMethodByNormParams) ([]ContactMethod, error)
	FindExternalID(ctx context.Context, arg FindExternalIDParams) (ExternalID, error)
	// Guards the import cutover against re-importing the same paid-through value:
	// a second import of unchanged data must not append a duplicate decision.
	FindImportCoverageEvent(ctx context.Context, arg FindImportCoverageEventParams) (CoverageEvent, error)
	// Posted-payment corrections.
	//
	// Nothing here updates or deletes a payment. A correction appends a signed
	// reversal and a positive replacement and links the three together, so the
	// original stays exactly as it was recorded.
	// Walking a chain forward uses GetPaymentCorrectionByOriginal from
	// treasury.sql: the correction that superseded a payment is the one whose
	// original_payment_id is that payment.
	// Net totals over the posted ledger rather than the frozen draft entries. After
	// a correction the two legitimately differ: the entries record what was typed,
	// the ledger records what the club actually holds.
	GetBatchLedgerTotals(ctx context.Context, batchID sql.NullInt64) (GetBatchLedgerTotalsRow, error)
	GetChangeRequest(ctx context.Context, id int64) (MemberChangeRequest, error)
	GetChangeRequestItem(ctx context.Context, id int64) (MemberChangeRequestItem, error)
	GetContactMethod(ctx context.Context, id int64) (ContactMethod, error)
	GetCoverageEvent(ctx context.Context, id int64) (CoverageEvent, error)
	// The coverage decision a given payment granted, if it granted one.
	GetCoverageEventByPayment(ctx context.Context, paymentID sql.NullInt64) (CoverageEvent, error)
	// Phase 2 ledger primitives. Domain services compose these; no query here
	// derives a paid-through date from an amount.
	GetDuesRate(ctx context.Context, year int64) (DuesRate, error)
	// The currently effective decision is the newest event that nothing supersedes.
	GetEffectiveCoverageEvent(ctx context.Context, membershipID int64) (CoverageEvent, error)
	GetEmailLinkByTokenHash(ctx context.Context, tokenHash string) (EmailLink, error)
	GetFCCVerification(ctx context.Context, id int64) (FccVerification, error)
	GetHonoraryGrant(ctx context.Context, id int64) (HonoraryGrant, error)
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error)
	GetImportRun(ctx context.Context, id int64) (ImportRun, error)
	GetImportRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (ImportRun, error)
	GetLatestAcsAresSharing(ctx context.Context, personID int64) (AcsAresSharingEvent, error)
	GetLatestVisibility(ctx context.Context, contactMethodID int64) (ContactMethodVisibilityEvent, error)
	GetMemberAccessGrant(ctx context.Context, id int64) (MemberAccessGrant, error)
	GetMembership(ctx context.Context, id int64) (Membership, error)
	GetNote(ctx context.Context, id int64) (Note, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetPaymentBatch(ctx context.Context, id int64) (PaymentBatch, error)
	GetPaymentBatchEntry(ctx context.Context, id int64) (PaymentBatchEntry, error)
	// Totals are always calculated by the server. A client never submits one.
	GetPaymentBatchTotals(ctx context.Context, batchID int64) (GetPaymentBatchTotalsRow, error)
	GetPaymentCorrectionByOriginal(ctx context.Context, originalPaymentID int64) (PaymentCorrection, error)
	GetPaymentWithMember(ctx context.Context, id int64) (GetPaymentWithMemberRow, error)
	GetPerson(ctx context.Context, id int64) (Person, error)
	GetPersonByCallSign(ctx context.Context, callSign sql.NullString) (Person, error)
	GetPersonRelationship(ctx context.Context, id int64) (PersonRelationship, error)
	//
	// One active contact per kind for the worksheet snapshot: the one marked
	// primary, or failing that the lowest active id.
	//
	// The previous version took MAX over every active value and never read
	// is_primary, so a member with two active addresses had whichever sorted later
	// printed on the sheet. Lexical order is not a proxy for what the member asked
	// to be contacted on. The id fallback is arbitrary but stable and explainable:
	// the earliest recorded contact wins when nobody has chosen.
	GetPrimaryContact(ctx context.Context, personID int64) (GetPrimaryContactRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetStagedRow(ctx context.Context, id int64) (StagedImportRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWorksheetRun(ctx context.Context, id int64) (DuesWorksheetRun, error)
	// Member record access grants.
	//
	// This file is the ONLY way authorization learns which person records a user
	// may see. Nothing here joins users.person_id, contact_methods.value_norm,
	// person_relationships, or role_capabilities: an access decision comes from an
	// explicit unrevoked grant or it does not exist.
	//
	// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character above a query corrupts the SQL it parses.
	GrantMemberAccess(ctx context.Context, arg GrantMemberAccessParams) (MemberAccessGrant, error)
	IncrementFailedLogin(ctx context.Context, id int64) error
	InsertDuesRate(ctx context.Context, arg InsertDuesRateParams) (DuesRate, error)
	//
	// Officer view. Includes revoked rows so the history of who could see a record
	// is readable, not just the current state.
	ListAccessGrantsForPerson(ctx context.Context, personID int64) ([]ListAccessGrantsForPersonRow, error)
	//
	// The officer view of one account: every grant it has ever held, revoked ones
	// included, so "who could reach this record, and when" stays answerable.
	//
	// Distinct from ListActiveAccessGrantsForUser, which is the authorization read
	// and must return only what currently confers access. Keeping them separate
	// means a history view can never accidentally become an authorization answer.
	ListAccessGrantsForUser(ctx context.Context, userID int64) ([]ListAccessGrantsForUserRow, error)
	ListAcsAresSharingHistory(ctx context.Context, personID int64) ([]AcsAresSharingEvent, error)
	//
	// The authorization read. Loaded per request, so revoking a grant takes effect
	// inside a session that is already open.
	ListActiveAccessGrantsForUser(ctx context.Context, userID int64) ([]ListActiveAccessGrantsForUserRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error)
	ListCapabilities(ctx context.Context) ([]Capability, error)
	ListChangeRequestItems(ctx context.Context, requestID int64) ([]MemberChangeRequestItem, error)
	//
	// The officer queue. Every filter is optional: pass NULL for status, source, or
	// requester to ignore it, and 0 for untargeted_only to include linked requests.
	//
	// Ordering is submitted_at DESC with an id tie-breaker so a page boundary is
	// deterministic. Without the tie-breaker two requests recorded in the same
	// millisecond could swap places between calls and hide a row from a caller
	// paging through the queue.
	ListChangeRequests(ctx context.Context, arg ListChangeRequestsParams) ([]ListChangeRequestsRow, error)
	//
	// A member's own request history. Scoped by requester, never by target, so it
	// cannot become a read of someone else's record.
	ListChangeRequestsForRequester(ctx context.Context, arg ListChangeRequestsForRequesterParams) ([]MemberChangeRequest, error)
	ListContactMethods(ctx context.Context, personID int64) ([]ContactMethod, error)
	// The corrections that touched a batch, for its plain-language activity log.
	ListCorrectionsByBatch(ctx context.Context, batchID sql.NullInt64) ([]ListCorrectionsByBatchRow, error)
	ListCoverageEventsByMembership(ctx context.Context, membershipID int64) ([]CoverageEvent, error)
	ListCoverageEventsPage(ctx context.Context, arg ListCoverageEventsPageParams) ([]CoverageEvent, error)
	ListDecisionsForRow(ctx context.Context, stagedImportRowID int64) ([]ReconciliationDecision, error)
	//
	// EVERY shared contact for the members on one page.
	//
	// A member may share more than one number, and both can matter: a member whose
	// mobile has no signal at home needs the landline listed too. Returning one
	// contact per kind silently dropped the rest (bcars-portal-4ux.14).
	//
	// The page CTE repeats the listing's population, filter, ordering, and bounds,
	// so this returns contacts for exactly the members on that page and no others.
	// That is why there is no per-member query and no N+1.
	//
	// A contact survives only when the latest visibility decision for it permits
	// full_members. With no decision on file it falls back to the Phase 1 domain
	// default: a Full member's contact is shareable with Full members, an
	// Associate's is not. An imported import_default event is a recorded decision
	// like any other, so it keeps its result until an officer supersedes it.
	//
	// Primary first, then by id, so a member's main number leads.
	ListDirectoryContacts(ctx context.Context, arg ListDirectoryContactsParams) ([]ListDirectoryContactsRow, error)
	//
	// Rows are active approved members, optionally narrowed to one membership type.
	// Contact values are NOT here; see ListDirectoryContacts, which returns every
	// shared contact rather than one per kind.
	//
	// Ordering is by sort_name then person id. The id tie-breaker keeps a page
	// boundary from shifting between calls when two members sort equally, so paging
	// cannot silently skip someone.
	ListDirectoryEntries(ctx context.Context, arg ListDirectoryEntriesParams) ([]ListDirectoryEntriesRow, error)
	ListDuesRates(ctx context.Context) ([]DuesRate, error)
	// Derived dues standing and coverage reads.
	//
	// Standing is never stored. It is computed as of an explicit date so that
	// tests, worksheets, and reports are deterministic. `expiring` in particular is
	// a classification of this query, not a state any row carries.
	//
	// One row per membership with its effective coverage decision, any active
	// honorary waiver, and the derived status. Serves both the filtered list and
	// the single-membership lookup: pass membership_id = 0 to list, or a specific
	// id to fetch one. include_ended = 1 keeps resigned/rejected/deceased rows,
	// which the single lookup needs and the working list does not want.
	//
	// The status filter below repeats the CASE arms as predicates rather than
	// filtering on the alias, which SQLite does not allow in WHERE. Each arm must
	// stay the exact complement of its CASE arm, or a filtered list would return
	// rows labelled with a status other than the one that was asked for.
	ListDuesStanding(ctx context.Context, arg ListDuesStandingParams) ([]ListDuesStandingRow, error)
	ListExternalIDsForEntity(ctx context.Context, arg ListExternalIDsForEntityParams) ([]ExternalID, error)
	ListFCCVerificationsByMembership(ctx context.Context, membershipID int64) ([]FccVerification, error)
	ListHonoraryGrantsByMembership(ctx context.Context, membershipID int64) ([]HonoraryGrant, error)
	ListImportRuns(ctx context.Context, arg ListImportRunsParams) ([]ImportRun, error)
	// Treasury history and reporting reads.
	//
	// Every query here is treasury-only. Nothing in this file is reachable without
	// payment.read or payment.export, and no result feeds a safe dues-standing
	// response.
	//
	// The books view. effective_only = 1 hides the rows a correction has already
	// settled (reversals, and originals that were replaced), leaving what the club
	// currently holds. effective_only = 0 shows the whole audit trail.
	//
	// Filters are all optional: 0 or '' means "no filter". They bind once in the
	// params CTE and join in as columns, which keeps each sqlc.arg out of the CASE
	// and WHERE expressions sqlc's SQLite analyzer struggles with.
	//
	// Keep every comment in this file ASCII. sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character anywhere above a query shifts the offsets
	// and silently corrupts the SQL it hands the parser, which then fails on a
	// mangled LIMIT or OFFSET far from the real cause.
	//
	// The correction join cannot fan out: the schema allows at most one correction
	// record per payment.
	ListLedgerPayments(ctx context.Context, arg ListLedgerPaymentsParams) ([]ListLedgerPaymentsRow, error)
	ListMembershipsByPerson(ctx context.Context, personID int64) ([]Membership, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
	ListPaymentBatchEntries(ctx context.Context, batchID int64) ([]PaymentBatchEntry, error)
	// Draft payment batches and their mutable entries.
	//
	// Nothing in this file writes a payment or a coverage event. A draft batch is
	// deliberately inert until it is posted.
	ListPaymentBatches(ctx context.Context, arg ListPaymentBatchesParams) ([]PaymentBatch, error)
	ListPaymentsByBatch(ctx context.Context, batchID sql.NullInt64) ([]Payment, error)
	ListPaymentsByMembership(ctx context.Context, membershipID int64) ([]Payment, error)
	ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error)
	ListPersonsByName(ctx context.Context, arg ListPersonsByNameParams) ([]ListPersonsByNameRow, error)
	//
	// Both directions, active only. The related person's name comes along so a
	// caller does not need a second query; nothing else about them is exposed.
	ListRelationshipsForPerson(ctx context.Context, personID int64) ([]ListRelationshipsForPersonRow, error)
	ListRoleCapabilities(ctx context.Context) ([]RoleCapability, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListStagedRows(ctx context.Context, arg ListStagedRowsParams) ([]StagedImportRow, error)
	ListStagedRowsRequiringManual(ctx context.Context, arg ListStagedRowsRequiringManualParams) ([]StagedImportRow, error)
	//
	// Blind public intake awaiting an officer link.
	ListUntargetedChangeRequests(ctx context.Context, arg ListUntargetedChangeRequestsParams) ([]MemberChangeRequest, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVisibilityHistory(ctx context.Context, contactMethodID int64) ([]ContactMethodVisibilityEvent, error)
	// The memberships on an earlier sheet with no payment posted since it ran.
	ListWorksheetMembershipsUnpaidSince(ctx context.Context, runID int64) ([]int64, error)
	//
	// Rows as printed, plus whether a payment has been posted for that member since
	// the sheet was generated. The snapshot itself is never rewritten; this flag is
	// computed at read time, so an old sheet keeps saying what it said while still
	// telling the treasurer which lines are already done.
	ListWorksheetRows(ctx context.Context, arg ListWorksheetRowsParams) ([]ListWorksheetRowsRow, error)
	ListWorksheetRuns(ctx context.Context, arg ListWorksheetRunsParams) ([]DuesWorksheetRun, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	//
	// Stamps the resource an approved item produced. `applied_at IS NULL` in the
	// WHERE clause is what makes apply exactly-once: a replay updates no row, and
	// the caller returns the already-recorded outcome instead of applying twice.
	MarkChangeRequestItemApplied(ctx context.Context, arg MarkChangeRequestItemAppliedParams) (MemberChangeRequestItem, error)
	MarkDeceased(ctx context.Context, arg MarkDeceasedParams) (Person, error)
	MarkPaymentBatchAbandoned(ctx context.Context, arg MarkPaymentBatchAbandonedParams) (PaymentBatch, error)
	// Batch listing lives in batches.sql, where the state filter is optional.
	MarkPaymentBatchPosted(ctx context.Context, arg MarkPaymentBatchPostedParams) (PaymentBatch, error)
	// Sequence is stable and server-assigned: removing row 2 never renumbers row 3,
	// so a printed worksheet and the grid keep agreeing.
	NextPaymentBatchEntrySequence(ctx context.Context, batchID int64) (int64, error)
	ReactivatePerson(ctx context.Context, arg ReactivatePersonParams) (Person, error)
	// Request-attempt log backing the reusable abuse limiter.
	//
	// Every attempt is recorded regardless of outcome and regardless of whether the
	// target exists, so a count here never depends on an answer the endpoint is
	// trying not to reveal.
	//
	// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
	// offset, so a multi-byte character above a query corrupts the SQL it parses.
	RecordRequestAttempt(ctx context.Context, arg RecordRequestAttemptParams) (RequestAttempt, error)
	RejectMembership(ctx context.Context, arg RejectMembershipParams) (Membership, error)
	RevokeAllSessionsForUser(ctx context.Context, userID int64) error
	RevokeCapabilityGrant(ctx context.Context, arg RevokeCapabilityGrantParams) error
	RevokeFCCVerification(ctx context.Context, arg RevokeFCCVerificationParams) error
	RevokeHonoraryGrant(ctx context.Context, arg RevokeHonoraryGrantParams) (HonoraryGrant, error)
	//
	// Version-guarded, so a concurrent revoke cannot silently no-op. A caller that
	// gets sql.ErrNoRows maps it to db.ErrStale after confirming the row exists.
	RevokeMemberAccess(ctx context.Context, arg RevokeMemberAccessParams) (MemberAccessGrant, error)
	RevokeRoleGrant(ctx context.Context, arg RevokeRoleGrantParams) error
	RevokeSession(ctx context.Context, id string) error
	RoleExists(ctx context.Context, code string) (bool, error)
	// SearchAuditEvents is the general filtered listing behind GET /audit-events.
	// Every filter is optional (pass NULL to skip it) and all filters compose.
	// action is matched as a prefix (instr(...) = 1 rather than LIKE, so the
	// caller's value needs no wildcard escaping); the rest are exact matches.
	// The tiebreak on id keeps the order total, which offset paging requires.
	SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]AuditEvent, error)
	SetChangeRequestStatus(ctx context.Context, arg SetChangeRequestStatusParams) (MemberChangeRequest, error)
	//
	// Officer triage links a supplied hint to a canonical person. The supplied_*
	// snapshot is untouched: what the submitter said stays on the record.
	SetChangeRequestTarget(ctx context.Context, arg SetChangeRequestTargetParams) (MemberChangeRequest, error)
	SetPaymentBatchWorksheetRun(ctx context.Context, arg SetPaymentBatchWorksheetRunParams) error
	SetPrimary(ctx context.Context, id int64) error
	SetWorksheetRunRowCount(ctx context.Context, arg SetWorksheetRunRowCountParams) error
	SumPaymentBatchEntries(ctx context.Context, batchID int64) (SumPaymentBatchEntriesRow, error)
	// Bumps the batch version after an entry mutation, so a browser holding a
	// stale batch ETag cannot post a batch whose rows have since changed.
	TouchPaymentBatch(ctx context.Context, id int64) (PaymentBatch, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TransitionLifecycle(ctx context.Context, arg TransitionLifecycleParams) (Membership, error)
	UpdateContactMethod(ctx context.Context, arg UpdateContactMethodParams) (ContactMethod, error)
	// Version-guarded so a revision cannot silently overwrite another officer's.
	UpdateDuesRate(ctx context.Context, arg UpdateDuesRateParams) (DuesRate, error)
	// is_lifetime is written explicitly because the table CHECK forbids a lifetime
	// grant from carrying an end date; giving a grant an end date converts it to a
	// term grant.
	UpdateHonoraryGrant(ctx context.Context, arg UpdateHonoraryGrantParams) (HonoraryGrant, error)
	UpdateImportRunStatus(ctx context.Context, arg UpdateImportRunStatusParams) (ImportRun, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	// Version-guarded, and refuses a terminal batch: a posted or abandoned batch
	// accepts no further changes.
	UpdatePaymentBatchDefaults(ctx context.Context, arg UpdatePaymentBatchDefaultsParams) (PaymentBatch, error)
	UpdatePaymentBatchEntry(ctx context.Context, arg UpdatePaymentBatchEntryParams) (PaymentBatchEntry, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdatePersonRelationship(ctx context.Context, arg UpdatePersonRelationshipParams) (PersonRelationship, error)
	UpdateStagedRowAction(ctx context.Context, arg UpdateStagedRowActionParams) (StagedImportRow, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
