// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archivePersonRelationship = `-- name: ArchivePersonRelationship :one
UPDATE person_relationships
   SET archived_at = ?1,
       archived_by = ?2,
       archive_reason = ?3,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?4
   AND version = ?5
   AND archived_at IS NULL
RETURNING id, from_person_id, to_person_id, kind, context, created_by, archived_at, archived_by, archive_reason, created_at, updated_at, version
`

type ArchivePersonRelationshipParams struct {
	ArchivedAt    sql.NullString
	ArchivedBy    sql.NullInt64
	ArchiveReason sql.NullString
	ID            int64
	Version       int64
}

func (q *Queries) ArchivePersonRelationship(ctx context.Context, arg ArchivePersonRelationshipParams) (PersonRelationship, error) {
	row := q.db.QueryRowContext(ctx, archivePersonRelationship,
		arg.ArchivedAt,
		arg.ArchivedBy,
		arg.ArchiveReason,
		arg.ID,
		arg.Version,
	)
	var i PersonRelationship
	err := row.Scan(
		&i.ID,
		&i.FromPersonID,
		&i.ToPersonID,
		&i.Kind,
		&i.Context,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createPersonRelationship = `-- name: CreatePersonRelationship :one

INSERT INTO person_relationships (
    from_person_id, to_person_id, kind, context, created_by
) VALUES (?, ?, ?, ?, ?)
RETURNING id, from_person_id, to_person_id, kind, context, created_by, archived_at, archived_by, archive_reason, created_at, updated_at, version
`

type CreatePersonRelationshipParams struct {
	FromPersonID int64
	ToPersonID   int64
	Kind         string
	Context      sql.NullString
	CreatedBy    sql.NullInt64
}

// Informational person relationships.
//
// These queries are read and write only against person_relationships. None of
// them touches member_access_grants, sessions, users, or role_capabilities,
// because a relationship confers no authority. Adding a spouse does not let
// either person see the other's record; an officer grants that separately.
//
// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
// offset, so a multi-byte character above a query corrupts the SQL it parses.
func (q *Queries) CreatePersonRelationship(ctx context.Context, arg CreatePersonRelationshipParams) (PersonRelationship, error) {
	row := q.db.QueryRowContext(ctx, createPersonRelationship,
		arg.FromPersonID,
		arg.ToPersonID,
		arg.Kind,
		arg.Context,
		arg.CreatedBy,
	)
	var i PersonRelationship
	err := row.Scan(
		&i.ID,
		&i.FromPersonID,
		&i.ToPersonID,
		&i.Kind,
		&i.Context,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPersonRelationship = `-- name: GetPersonRelationship :one
SELECT id, from_person_id, to_person_id, kind, context, created_by, archived_at, archived_by, archive_reason, created_at, updated_at, version FROM person_relationships WHERE id = ?
`

func (q *Queries) GetPersonRelationship(ctx context.Context, id int64) (PersonRelationship, error) {
	row := q.db.QueryRowContext(ctx, getPersonRelationship, id)
	var i PersonRelationship
	err := row.Scan(
		&i.ID,
		&i.FromPersonID,
		&i.ToPersonID,
		&i.Kind,
		&i.Context,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listRelationshipsForPerson = `-- name: ListRelationshipsForPerson :many
SELECT r.id             AS relationship_id,
       r.kind           AS kind,
       r.context        AS context,
       r.from_person_id AS from_person_id,
       r.to_person_id   AS to_person_id,
       r.created_at     AS created_at,
       r.version        AS version,
       CAST(CASE WHEN r.from_person_id = ?1 THEN 'outgoing'
                 ELSE 'incoming' END AS TEXT) AS direction,
       other.display_name AS other_display_name,
       other.call_sign    AS other_call_sign
  FROM person_relationships r
  JOIN persons other
    ON other.id = CASE WHEN r.from_person_id = ?1
                       THEN r.to_person_id ELSE r.from_person_id END
 WHERE (r.from_person_id = ?1 OR r.to_person_id = ?1)
   AND r.archived_at IS NULL
 ORDER BY other.sort_name, r.id
`

type ListRelationshipsForPersonRow struct {
	RelationshipID   int64
	Kind             string
	Context          sql.NullString
	FromPersonID     int64
	ToPersonID       int64
	CreatedAt        string
	Version          int64
	Direction        string
	OtherDisplayName string
	OtherCallSign    sql.NullString
}

// Both directions, active only. The related person's name comes along so a
// caller does not need a second query; nothing else about them is exposed.
func (q *Queries) ListRelationshipsForPerson(ctx context.Context, personID int64) ([]ListRelationshipsForPersonRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationshipsForPersonRow{}
	for rows.Next() {
		var i ListRelationshipsForPersonRow
		if err := rows.Scan(
			&i.RelationshipID,
			&i.Kind,
			&i.Context,
			&i.FromPersonID,
			&i.ToPersonID,
			&i.CreatedAt,
			&i.Version,
			&i.Direction,
			&i.OtherDisplayName,
			&i.OtherCallSign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonRelationship = `-- name: UpdatePersonRelationship :one
UPDATE person_relationships
   SET kind = ?1,
       context = ?2,
       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
       version = version + 1
 WHERE id = ?3
   AND version = ?4
   AND archived_at IS NULL
RETURNING id, from_person_id, to_person_id, kind, context, created_by, archived_at, archived_by, archive_reason, created_at, updated_at, version
`

type UpdatePersonRelationshipParams struct {
	Kind    string
	Context sql.NullString
	ID      int64
	Version int64
}

func (q *Queries) UpdatePersonRelationship(ctx context.Context, arg UpdatePersonRelationshipParams) (PersonRelationship, error) {
	row := q.db.QueryRowContext(ctx, updatePersonRelationship,
		arg.Kind,
		arg.Context,
		arg.ID,
		arg.Version,
	)
	var i PersonRelationship
	err := row.Scan(
		&i.ID,
		&i.FromPersonID,
		&i.ToPersonID,
		&i.Kind,
		&i.Context,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
