// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_attempts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countRequestAttemptsBySource = `-- name: CountRequestAttemptsBySource :one
SELECT count(*) FROM request_attempts
 WHERE operation = ?
   AND source_hash = ?
   AND attempted_at >= ?
`

type CountRequestAttemptsBySourceParams struct {
	Operation   string
	SourceHash  sql.NullString
	AttemptedAt string
}

// Attempts from one source within the window, whatever their outcome. Counting
// limited attempts too means sustained hammering keeps extending the block
// rather than draining it, which is the intended behaviour for abuse.
func (q *Queries) CountRequestAttemptsBySource(ctx context.Context, arg CountRequestAttemptsBySourceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestAttemptsBySource, arg.Operation, arg.SourceHash, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestAttemptsByTarget = `-- name: CountRequestAttemptsByTarget :one
SELECT count(*) FROM request_attempts
 WHERE operation = ?
   AND target_hash = ?
   AND attempted_at >= ?
`

type CountRequestAttemptsByTargetParams struct {
	Operation   string
	TargetHash  sql.NullString
	AttemptedAt string
}

func (q *Queries) CountRequestAttemptsByTarget(ctx context.Context, arg CountRequestAttemptsByTargetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestAttemptsByTarget, arg.Operation, arg.TargetHash, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRequestAttemptsBefore = `-- name: DeleteRequestAttemptsBefore :exec
DELETE FROM request_attempts WHERE attempted_at < ?
`

// Pruning. The table is an abuse control, not a retention record; rows older
// than the longest window answer no question.
func (q *Queries) DeleteRequestAttemptsBefore(ctx context.Context, attemptedAt string) error {
	_, err := q.db.ExecContext(ctx, deleteRequestAttemptsBefore, attemptedAt)
	return err
}

const recordRequestAttempt = `-- name: RecordRequestAttempt :one

INSERT INTO request_attempts (operation, source_hash, target_hash, outcome, attempted_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, operation, source_hash, target_hash, outcome, attempted_at, created_at
`

type RecordRequestAttemptParams struct {
	Operation   string
	SourceHash  sql.NullString
	TargetHash  sql.NullString
	Outcome     string
	AttemptedAt string
}

// Request-attempt log backing the reusable abuse limiter.
//
// Every attempt is recorded regardless of outcome and regardless of whether the
// target exists, so a count here never depends on an answer the endpoint is
// trying not to reveal.
//
// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
// offset, so a multi-byte character above a query corrupts the SQL it parses.
func (q *Queries) RecordRequestAttempt(ctx context.Context, arg RecordRequestAttemptParams) (RequestAttempt, error) {
	row := q.db.QueryRowContext(ctx, recordRequestAttempt,
		arg.Operation,
		arg.SourceHash,
		arg.TargetHash,
		arg.Outcome,
		arg.AttemptedAt,
	)
	var i RequestAttempt
	err := row.Scan(
		&i.ID,
		&i.Operation,
		&i.SourceHash,
		&i.TargetHash,
		&i.Outcome,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}
