// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: treasury.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createCoverageEvent = `-- name: CreateCoverageEvent :one
INSERT INTO coverage_events (
    membership_id, paid_through, reason_kind, reason, payment_id,
    import_run_id, supersedes_event_id, source_note, decided_by, decided_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, membership_id, paid_through, reason_kind, reason, payment_id, import_run_id, supersedes_event_id, source_note, decided_by, decided_at, created_at
`

type CreateCoverageEventParams struct {
	MembershipID      int64
	PaidThrough       string
	ReasonKind        string
	Reason            sql.NullString
	PaymentID         sql.NullInt64
	ImportRunID       sql.NullInt64
	SupersedesEventID sql.NullInt64
	SourceNote        sql.NullString
	DecidedBy         sql.NullInt64
	DecidedAt         string
}

func (q *Queries) CreateCoverageEvent(ctx context.Context, arg CreateCoverageEventParams) (CoverageEvent, error) {
	row := q.db.QueryRowContext(ctx, createCoverageEvent,
		arg.MembershipID,
		arg.PaidThrough,
		arg.ReasonKind,
		arg.Reason,
		arg.PaymentID,
		arg.ImportRunID,
		arg.SupersedesEventID,
		arg.SourceNote,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	var i CoverageEvent
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.PaidThrough,
		&i.ReasonKind,
		&i.Reason,
		&i.PaymentID,
		&i.ImportRunID,
		&i.SupersedesEventID,
		&i.SourceNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one
INSERT INTO idempotency_records (
    actor_user_id, operation, idempotency_key, request_hash, resource_kind, resource_id
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, actor_user_id, operation, idempotency_key, request_hash, resource_kind, resource_id, created_at
`

type CreateIdempotencyRecordParams struct {
	ActorUserID    int64
	Operation      string
	IdempotencyKey string
	RequestHash    string
	ResourceKind   sql.NullString
	ResourceID     sql.NullInt64
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, createIdempotencyRecord,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResourceKind,
		arg.ResourceID,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResourceKind,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    membership_id, batch_id, amount_cents, method, reference, received_on,
    received_by_officer, entered_by, entered_at, receipt_code, entry_kind,
    corrects_payment_id, treasurer_note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, membership_id, batch_id, amount_cents, method, reference, received_on, received_by_officer, entered_by, entered_at, receipt_code, entry_kind, corrects_payment_id, treasurer_note, created_at
`

type CreatePaymentParams struct {
	MembershipID      int64
	BatchID           sql.NullInt64
	AmountCents       int64
	Method            string
	Reference         sql.NullString
	ReceivedOn        string
	ReceivedByOfficer sql.NullString
	EnteredBy         int64
	EnteredAt         string
	ReceiptCode       string
	EntryKind         string
	CorrectsPaymentID sql.NullInt64
	TreasurerNote     sql.NullString
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.MembershipID,
		arg.BatchID,
		arg.AmountCents,
		arg.Method,
		arg.Reference,
		arg.ReceivedOn,
		arg.ReceivedByOfficer,
		arg.EnteredBy,
		arg.EnteredAt,
		arg.ReceiptCode,
		arg.EntryKind,
		arg.CorrectsPaymentID,
		arg.TreasurerNote,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.BatchID,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.ReceivedOn,
		&i.ReceivedByOfficer,
		&i.EnteredBy,
		&i.EnteredAt,
		&i.ReceiptCode,
		&i.EntryKind,
		&i.CorrectsPaymentID,
		&i.TreasurerNote,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentBatch = `-- name: CreatePaymentBatch :one

INSERT INTO payment_batches (label, default_amount_cents, default_paid_through, opened_by, opened_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version, worksheet_run_id
`

type CreatePaymentBatchParams struct {
	Label              string
	DefaultAmountCents sql.NullInt64
	DefaultPaidThrough sql.NullString
	OpenedBy           int64
	OpenedAt           string
}

// Rate writes live in dues.sql: InsertDuesRate and the version-guarded
// UpdateDuesRate. There is deliberately no blind upsert, so a revision cannot
// overwrite another officer's without presenting the version it saw.
func (q *Queries) CreatePaymentBatch(ctx context.Context, arg CreatePaymentBatchParams) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, createPaymentBatch,
		arg.Label,
		arg.DefaultAmountCents,
		arg.DefaultPaidThrough,
		arg.OpenedBy,
		arg.OpenedAt,
	)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.State,
		&i.DefaultAmountCents,
		&i.DefaultPaidThrough,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.AbandonedBy,
		&i.AbandonedAt,
		&i.AbandonReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.WorksheetRunID,
	)
	return i, err
}

const createPaymentBatchEntry = `-- name: CreatePaymentBatchEntry :one
INSERT INTO payment_batch_entries (
    batch_id, membership_id, sequence, amount_cents, method, reference,
    received_on, received_by_officer, paid_through, treasurer_note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, batch_id, membership_id, sequence, amount_cents, method, reference, received_on, received_by_officer, paid_through, treasurer_note, created_at, updated_at, version
`

type CreatePaymentBatchEntryParams struct {
	BatchID           int64
	MembershipID      int64
	Sequence          int64
	AmountCents       int64
	Method            string
	Reference         sql.NullString
	ReceivedOn        string
	ReceivedByOfficer sql.NullString
	PaidThrough       string
	TreasurerNote     sql.NullString
}

func (q *Queries) CreatePaymentBatchEntry(ctx context.Context, arg CreatePaymentBatchEntryParams) (PaymentBatchEntry, error) {
	row := q.db.QueryRowContext(ctx, createPaymentBatchEntry,
		arg.BatchID,
		arg.MembershipID,
		arg.Sequence,
		arg.AmountCents,
		arg.Method,
		arg.Reference,
		arg.ReceivedOn,
		arg.ReceivedByOfficer,
		arg.PaidThrough,
		arg.TreasurerNote,
	)
	var i PaymentBatchEntry
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.MembershipID,
		&i.Sequence,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.ReceivedOn,
		&i.ReceivedByOfficer,
		&i.PaidThrough,
		&i.TreasurerNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createPaymentCorrection = `-- name: CreatePaymentCorrection :one
INSERT INTO payment_corrections (
    original_payment_id, reversal_payment_id, replacement_payment_id,
    reason, corrected_by, corrected_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, original_payment_id, reversal_payment_id, replacement_payment_id, reason, corrected_by, corrected_at, created_at
`

type CreatePaymentCorrectionParams struct {
	OriginalPaymentID    int64
	ReversalPaymentID    int64
	ReplacementPaymentID int64
	Reason               string
	CorrectedBy          int64
	CorrectedAt          string
}

func (q *Queries) CreatePaymentCorrection(ctx context.Context, arg CreatePaymentCorrectionParams) (PaymentCorrection, error) {
	row := q.db.QueryRowContext(ctx, createPaymentCorrection,
		arg.OriginalPaymentID,
		arg.ReversalPaymentID,
		arg.ReplacementPaymentID,
		arg.Reason,
		arg.CorrectedBy,
		arg.CorrectedAt,
	)
	var i PaymentCorrection
	err := row.Scan(
		&i.ID,
		&i.OriginalPaymentID,
		&i.ReversalPaymentID,
		&i.ReplacementPaymentID,
		&i.Reason,
		&i.CorrectedBy,
		&i.CorrectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePaymentBatchEntry = `-- name: DeletePaymentBatchEntry :execresult
DELETE FROM payment_batch_entries WHERE id = ? AND version = ?
`

type DeletePaymentBatchEntryParams struct {
	ID      int64
	Version int64
}

func (q *Queries) DeletePaymentBatchEntry(ctx context.Context, arg DeletePaymentBatchEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePaymentBatchEntry, arg.ID, arg.Version)
}

const getDuesRate = `-- name: GetDuesRate :one

SELECT year, amount_cents, note, set_by, set_at, created_at, updated_at, version FROM dues_rates WHERE year = ?
`

// Phase 2 ledger primitives. Domain services compose these; no query here
// derives a paid-through date from an amount.
func (q *Queries) GetDuesRate(ctx context.Context, year int64) (DuesRate, error) {
	row := q.db.QueryRowContext(ctx, getDuesRate, year)
	var i DuesRate
	err := row.Scan(
		&i.Year,
		&i.AmountCents,
		&i.Note,
		&i.SetBy,
		&i.SetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getEffectiveCoverageEvent = `-- name: GetEffectiveCoverageEvent :one
SELECT id, membership_id, paid_through, reason_kind, reason, payment_id, import_run_id, supersedes_event_id, source_note, decided_by, decided_at, created_at FROM coverage_events c
WHERE c.membership_id = ?
  AND NOT EXISTS (SELECT 1 FROM coverage_events s WHERE s.supersedes_event_id = c.id)
ORDER BY c.decided_at DESC, c.id DESC
LIMIT 1
`

// The currently effective decision is the newest event that nothing supersedes.
func (q *Queries) GetEffectiveCoverageEvent(ctx context.Context, membershipID int64) (CoverageEvent, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveCoverageEvent, membershipID)
	var i CoverageEvent
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.PaidThrough,
		&i.ReasonKind,
		&i.Reason,
		&i.PaymentID,
		&i.ImportRunID,
		&i.SupersedesEventID,
		&i.SourceNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, actor_user_id, operation, idempotency_key, request_hash, resource_kind, resource_id, created_at FROM idempotency_records
WHERE actor_user_id = ? AND operation = ? AND idempotency_key = ?
`

type GetIdempotencyRecordParams struct {
	ActorUserID    int64
	Operation      string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyRecord, arg.ActorUserID, arg.Operation, arg.IdempotencyKey)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResourceKind,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, membership_id, batch_id, amount_cents, method, reference, received_on, received_by_officer, entered_by, entered_at, receipt_code, entry_kind, corrects_payment_id, treasurer_note, created_at FROM payments WHERE id = ?
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.BatchID,
		&i.AmountCents,
		&i.Method,
		&i.Reference,
		&i.ReceivedOn,
		&i.ReceivedByOfficer,
		&i.EnteredBy,
		&i.EnteredAt,
		&i.ReceiptCode,
		&i.EntryKind,
		&i.CorrectsPaymentID,
		&i.TreasurerNote,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentBatch = `-- name: GetPaymentBatch :one
SELECT id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version, worksheet_run_id FROM payment_batches WHERE id = ?
`

func (q *Queries) GetPaymentBatch(ctx context.Context, id int64) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, getPaymentBatch, id)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.State,
		&i.DefaultAmountCents,
		&i.DefaultPaidThrough,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.AbandonedBy,
		&i.AbandonedAt,
		&i.AbandonReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.WorksheetRunID,
	)
	return i, err
}

const getPaymentCorrectionByOriginal = `-- name: GetPaymentCorrectionByOriginal :one
SELECT id, original_payment_id, reversal_payment_id, replacement_payment_id, reason, corrected_by, corrected_at, created_at FROM payment_corrections WHERE original_payment_id = ?
`

func (q *Queries) GetPaymentCorrectionByOriginal(ctx context.Context, originalPaymentID int64) (PaymentCorrection, error) {
	row := q.db.QueryRowContext(ctx, getPaymentCorrectionByOriginal, originalPaymentID)
	var i PaymentCorrection
	err := row.Scan(
		&i.ID,
		&i.OriginalPaymentID,
		&i.ReversalPaymentID,
		&i.ReplacementPaymentID,
		&i.Reason,
		&i.CorrectedBy,
		&i.CorrectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCoverageEventsByMembership = `-- name: ListCoverageEventsByMembership :many
SELECT id, membership_id, paid_through, reason_kind, reason, payment_id, import_run_id, supersedes_event_id, source_note, decided_by, decided_at, created_at FROM coverage_events
WHERE membership_id = ?
ORDER BY decided_at DESC, id DESC
`

func (q *Queries) ListCoverageEventsByMembership(ctx context.Context, membershipID int64) ([]CoverageEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCoverageEventsByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageEvent{}
	for rows.Next() {
		var i CoverageEvent
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.PaidThrough,
			&i.ReasonKind,
			&i.Reason,
			&i.PaymentID,
			&i.ImportRunID,
			&i.SupersedesEventID,
			&i.SourceNote,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuesRates = `-- name: ListDuesRates :many
SELECT year, amount_cents, note, set_by, set_at, created_at, updated_at, version FROM dues_rates ORDER BY year DESC
`

func (q *Queries) ListDuesRates(ctx context.Context) ([]DuesRate, error) {
	rows, err := q.db.QueryContext(ctx, listDuesRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuesRate{}
	for rows.Next() {
		var i DuesRate
		if err := rows.Scan(
			&i.Year,
			&i.AmountCents,
			&i.Note,
			&i.SetBy,
			&i.SetAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentBatchEntries = `-- name: ListPaymentBatchEntries :many
SELECT id, batch_id, membership_id, sequence, amount_cents, method, reference, received_on, received_by_officer, paid_through, treasurer_note, created_at, updated_at, version FROM payment_batch_entries WHERE batch_id = ? ORDER BY sequence, id
`

func (q *Queries) ListPaymentBatchEntries(ctx context.Context, batchID int64) ([]PaymentBatchEntry, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentBatchEntries, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentBatchEntry{}
	for rows.Next() {
		var i PaymentBatchEntry
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.MembershipID,
			&i.Sequence,
			&i.AmountCents,
			&i.Method,
			&i.Reference,
			&i.ReceivedOn,
			&i.ReceivedByOfficer,
			&i.PaidThrough,
			&i.TreasurerNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByBatch = `-- name: ListPaymentsByBatch :many
SELECT id, membership_id, batch_id, amount_cents, method, reference, received_on, received_by_officer, entered_by, entered_at, receipt_code, entry_kind, corrects_payment_id, treasurer_note, created_at FROM payments WHERE batch_id = ? ORDER BY id
`

func (q *Queries) ListPaymentsByBatch(ctx context.Context, batchID sql.NullInt64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.BatchID,
			&i.AmountCents,
			&i.Method,
			&i.Reference,
			&i.ReceivedOn,
			&i.ReceivedByOfficer,
			&i.EnteredBy,
			&i.EnteredAt,
			&i.ReceiptCode,
			&i.EntryKind,
			&i.CorrectsPaymentID,
			&i.TreasurerNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByMembership = `-- name: ListPaymentsByMembership :many
SELECT id, membership_id, batch_id, amount_cents, method, reference, received_on, received_by_officer, entered_by, entered_at, receipt_code, entry_kind, corrects_payment_id, treasurer_note, created_at FROM payments WHERE membership_id = ? ORDER BY received_on DESC, id DESC
`

func (q *Queries) ListPaymentsByMembership(ctx context.Context, membershipID int64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.BatchID,
			&i.AmountCents,
			&i.Method,
			&i.Reference,
			&i.ReceivedOn,
			&i.ReceivedByOfficer,
			&i.EnteredBy,
			&i.EnteredAt,
			&i.ReceiptCode,
			&i.EntryKind,
			&i.CorrectsPaymentID,
			&i.TreasurerNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentBatchAbandoned = `-- name: MarkPaymentBatchAbandoned :one
UPDATE payment_batches
SET state = 'abandoned', abandoned_by = ?, abandoned_at = ?, abandon_reason = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ? AND state = 'open'
RETURNING id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version, worksheet_run_id
`

type MarkPaymentBatchAbandonedParams struct {
	AbandonedBy   sql.NullInt64
	AbandonedAt   sql.NullString
	AbandonReason sql.NullString
	ID            int64
	Version       int64
}

func (q *Queries) MarkPaymentBatchAbandoned(ctx context.Context, arg MarkPaymentBatchAbandonedParams) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, markPaymentBatchAbandoned,
		arg.AbandonedBy,
		arg.AbandonedAt,
		arg.AbandonReason,
		arg.ID,
		arg.Version,
	)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.State,
		&i.DefaultAmountCents,
		&i.DefaultPaidThrough,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.AbandonedBy,
		&i.AbandonedAt,
		&i.AbandonReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.WorksheetRunID,
	)
	return i, err
}

const markPaymentBatchPosted = `-- name: MarkPaymentBatchPosted :one

UPDATE payment_batches
SET state = 'posted', posted_by = ?, posted_at = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ? AND state = 'open'
RETURNING id, label, state, default_amount_cents, default_paid_through, opened_by, opened_at, posted_by, posted_at, abandoned_by, abandoned_at, abandon_reason, created_at, updated_at, version, worksheet_run_id
`

type MarkPaymentBatchPostedParams struct {
	PostedBy sql.NullInt64
	PostedAt sql.NullString
	ID       int64
	Version  int64
}

// Batch listing lives in batches.sql, where the state filter is optional.
func (q *Queries) MarkPaymentBatchPosted(ctx context.Context, arg MarkPaymentBatchPostedParams) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, markPaymentBatchPosted,
		arg.PostedBy,
		arg.PostedAt,
		arg.ID,
		arg.Version,
	)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.State,
		&i.DefaultAmountCents,
		&i.DefaultPaidThrough,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.AbandonedBy,
		&i.AbandonedAt,
		&i.AbandonReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.WorksheetRunID,
	)
	return i, err
}

const sumPaymentBatchEntries = `-- name: SumPaymentBatchEntries :one
SELECT COUNT(*) AS entry_count, COALESCE(SUM(amount_cents), 0) AS total_cents
FROM payment_batch_entries WHERE batch_id = ?
`

type SumPaymentBatchEntriesRow struct {
	EntryCount int64
	TotalCents interface{}
}

func (q *Queries) SumPaymentBatchEntries(ctx context.Context, batchID int64) (SumPaymentBatchEntriesRow, error) {
	row := q.db.QueryRowContext(ctx, sumPaymentBatchEntries, batchID)
	var i SumPaymentBatchEntriesRow
	err := row.Scan(&i.EntryCount, &i.TotalCents)
	return i, err
}
