// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worksheets.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createWorksheetRow = `-- name: CreateWorksheetRow :one
INSERT INTO dues_worksheet_rows (
    run_id, ordinal, membership_id, display_name, call_sign,
    base_type, dues_status, paid_through, email, phone
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, ordinal, membership_id, display_name, call_sign, base_type, dues_status, paid_through, email, phone, created_at
`

type CreateWorksheetRowParams struct {
	RunID        int64
	Ordinal      int64
	MembershipID int64
	DisplayName  string
	CallSign     sql.NullString
	BaseType     string
	DuesStatus   string
	PaidThrough  sql.NullString
	Email        sql.NullString
	Phone        sql.NullString
}

func (q *Queries) CreateWorksheetRow(ctx context.Context, arg CreateWorksheetRowParams) (DuesWorksheetRow, error) {
	row := q.db.QueryRowContext(ctx, createWorksheetRow,
		arg.RunID,
		arg.Ordinal,
		arg.MembershipID,
		arg.DisplayName,
		arg.CallSign,
		arg.BaseType,
		arg.DuesStatus,
		arg.PaidThrough,
		arg.Email,
		arg.Phone,
	)
	var i DuesWorksheetRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Ordinal,
		&i.MembershipID,
		&i.DisplayName,
		&i.CallSign,
		&i.BaseType,
		&i.DuesStatus,
		&i.PaidThrough,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const createWorksheetRun = `-- name: CreateWorksheetRun :one

INSERT INTO dues_worksheet_runs (
    label, as_of, filter_kind, source_run_id, sort_order,
    include_email, include_phone, warning_days, generated_by, generated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, label, as_of, filter_kind, source_run_id, sort_order, include_email, include_phone, warning_days, generated_by, generated_at, row_count, created_at
`

type CreateWorksheetRunParams struct {
	Label        sql.NullString
	AsOf         string
	FilterKind   string
	SourceRunID  sql.NullInt64
	SortOrder    string
	IncludeEmail int64
	IncludePhone int64
	WarningDays  int64
	GeneratedBy  int64
	GeneratedAt  string
}

// Renewal worksheet runs and their snapshot rows.
//
// Keep every comment in this file ASCII: sqlc substitutes sqlc.arg() by byte
// offset, so a multi-byte character above a query corrupts the SQL it parses.
func (q *Queries) CreateWorksheetRun(ctx context.Context, arg CreateWorksheetRunParams) (DuesWorksheetRun, error) {
	row := q.db.QueryRowContext(ctx, createWorksheetRun,
		arg.Label,
		arg.AsOf,
		arg.FilterKind,
		arg.SourceRunID,
		arg.SortOrder,
		arg.IncludeEmail,
		arg.IncludePhone,
		arg.WarningDays,
		arg.GeneratedBy,
		arg.GeneratedAt,
	)
	var i DuesWorksheetRun
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AsOf,
		&i.FilterKind,
		&i.SourceRunID,
		&i.SortOrder,
		&i.IncludeEmail,
		&i.IncludePhone,
		&i.WarningDays,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.RowCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPrimaryContact = `-- name: GetPrimaryContact :one
SELECT
    CAST(COALESCE(MAX(CASE WHEN kind = 'email' THEN value_norm END), '') AS TEXT) AS email,
    CAST(COALESCE(MAX(CASE WHEN kind = 'phone' THEN value_raw END), '') AS TEXT)  AS phone
FROM contact_methods
WHERE person_id = ? AND archived_at IS NULL
`

type GetPrimaryContactRow struct {
	Email string
	Phone string
}

// The member's current primary email and phone, for the worksheet snapshot.
func (q *Queries) GetPrimaryContact(ctx context.Context, personID int64) (GetPrimaryContactRow, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryContact, personID)
	var i GetPrimaryContactRow
	err := row.Scan(&i.Email, &i.Phone)
	return i, err
}

const getWorksheetRun = `-- name: GetWorksheetRun :one
SELECT id, label, as_of, filter_kind, source_run_id, sort_order, include_email, include_phone, warning_days, generated_by, generated_at, row_count, created_at FROM dues_worksheet_runs WHERE id = ?
`

func (q *Queries) GetWorksheetRun(ctx context.Context, id int64) (DuesWorksheetRun, error) {
	row := q.db.QueryRowContext(ctx, getWorksheetRun, id)
	var i DuesWorksheetRun
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AsOf,
		&i.FilterKind,
		&i.SourceRunID,
		&i.SortOrder,
		&i.IncludeEmail,
		&i.IncludePhone,
		&i.WarningDays,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.RowCount,
		&i.CreatedAt,
	)
	return i, err
}

const listWorksheetMembershipsUnpaidSince = `-- name: ListWorksheetMembershipsUnpaidSince :many
SELECT r.membership_id AS membership_id
  FROM dues_worksheet_rows r
  JOIN dues_worksheet_runs run ON run.id = r.run_id
 WHERE r.run_id = ?
   AND NOT EXISTS (
       SELECT 1 FROM payments pay
        WHERE pay.membership_id = r.membership_id
          AND pay.entry_kind <> 'reversal'
          AND pay.entered_at > run.generated_at
   )
 ORDER BY r.ordinal
`

// The memberships on an earlier sheet with no payment posted since it ran.
func (q *Queries) ListWorksheetMembershipsUnpaidSince(ctx context.Context, runID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listWorksheetMembershipsUnpaidSince, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var membership_id int64
		if err := rows.Scan(&membership_id); err != nil {
			return nil, err
		}
		items = append(items, membership_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksheetRows = `-- name: ListWorksheetRows :many
SELECT r.id            AS row_id,
       r.run_id        AS run_id,
       r.ordinal       AS ordinal,
       r.membership_id AS membership_id,
       r.display_name  AS display_name,
       r.call_sign     AS call_sign,
       r.base_type     AS base_type,
       r.dues_status   AS dues_status,
       r.paid_through  AS paid_through,
       r.email         AS email,
       r.phone         AS phone,
       CAST(CASE WHEN EXISTS (
           SELECT 1 FROM payments pay
            WHERE pay.membership_id = r.membership_id
              AND pay.entry_kind <> 'reversal'
              AND pay.entered_at > run.generated_at
       ) THEN 1 ELSE 0 END AS INTEGER) AS entered_since
  FROM dues_worksheet_rows r
  JOIN dues_worksheet_runs run ON run.id = r.run_id
 WHERE r.run_id = ?
 ORDER BY r.ordinal
 LIMIT ? OFFSET ?
`

type ListWorksheetRowsParams struct {
	RunID  int64
	Limit  int64
	Offset int64
}

type ListWorksheetRowsRow struct {
	RowID        int64
	RunID        int64
	Ordinal      int64
	MembershipID int64
	DisplayName  string
	CallSign     sql.NullString
	BaseType     string
	DuesStatus   string
	PaidThrough  sql.NullString
	Email        sql.NullString
	Phone        sql.NullString
	EnteredSince int64
}

// Rows as printed, plus whether a payment has been posted for that member since
// the sheet was generated. The snapshot itself is never rewritten; this flag is
// computed at read time, so an old sheet keeps saying what it said while still
// telling the treasurer which lines are already done.
func (q *Queries) ListWorksheetRows(ctx context.Context, arg ListWorksheetRowsParams) ([]ListWorksheetRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorksheetRows, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorksheetRowsRow{}
	for rows.Next() {
		var i ListWorksheetRowsRow
		if err := rows.Scan(
			&i.RowID,
			&i.RunID,
			&i.Ordinal,
			&i.MembershipID,
			&i.DisplayName,
			&i.CallSign,
			&i.BaseType,
			&i.DuesStatus,
			&i.PaidThrough,
			&i.Email,
			&i.Phone,
			&i.EnteredSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksheetRuns = `-- name: ListWorksheetRuns :many
SELECT id, label, as_of, filter_kind, source_run_id, sort_order, include_email, include_phone, warning_days, generated_by, generated_at, row_count, created_at FROM dues_worksheet_runs
ORDER BY generated_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListWorksheetRunsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListWorksheetRuns(ctx context.Context, arg ListWorksheetRunsParams) ([]DuesWorksheetRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorksheetRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuesWorksheetRun{}
	for rows.Next() {
		var i DuesWorksheetRun
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AsOf,
			&i.FilterKind,
			&i.SourceRunID,
			&i.SortOrder,
			&i.IncludeEmail,
			&i.IncludePhone,
			&i.WarningDays,
			&i.GeneratedBy,
			&i.GeneratedAt,
			&i.RowCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentBatchWorksheetRun = `-- name: SetPaymentBatchWorksheetRun :exec
UPDATE payment_batches SET worksheet_run_id = ? WHERE id = ?
`

type SetPaymentBatchWorksheetRunParams struct {
	WorksheetRunID sql.NullInt64
	ID             int64
}

func (q *Queries) SetPaymentBatchWorksheetRun(ctx context.Context, arg SetPaymentBatchWorksheetRunParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentBatchWorksheetRun, arg.WorksheetRunID, arg.ID)
	return err
}

const setWorksheetRunRowCount = `-- name: SetWorksheetRunRowCount :exec
UPDATE dues_worksheet_runs SET row_count = ? WHERE id = ?
`

type SetWorksheetRunRowCountParams struct {
	RowCount int64
	ID       int64
}

func (q *Queries) SetWorksheetRunRowCount(ctx context.Context, arg SetWorksheetRunRowCountParams) error {
	_, err := q.db.ExecContext(ctx, setWorksheetRunRowCount, arg.RowCount, arg.ID)
	return err
}
